/*
 * ConsolidateStockDiary.java
 *
 * Created on January 13, 2012, 1:25 AM
 */
package com.openbravo.pos.inventory;

import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;
import com.openbravo.format.Formats;
import java.util.Date;
import javax.swing.JOptionPane;
import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.DataRead;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializableRead;
import com.openbravo.data.loader.SerializerReadClass;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.format.Formats;
import com.openbravo.pos.clubmang.DataSourceProvider;
import com.openbravo.pos.clubmang.JasperReportNew;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactory;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.JPanelView;
import com.openbravo.pos.inventory.ConsolidateStockModel.ConsolidateStockReport;
import com.openbravo.pos.inventory.LocationInfo;
import com.openbravo.pos.reports.DataSourceWaiterTotal;
import com.openbravo.pos.reports.WaiterWiseTotalModel.waiterTotalSales;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author  user
 */
public class ConsolidateStockDiary extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {

    /** Creates new form ConsolidateStockDiary */
    private SentenceList m_sentlocations;
    private ComboBoxValModel m_LocationsModel;
    private String location;
    private DataLogicSales dlSales;
    private AppView m_App;
    private ConsolidateStockModel cmodel;

    public ConsolidateStockDiary() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        todate_buttn = new javax.swing.JButton();
        toDate_text = new javax.swing.JTextField();
        location1 = new javax.swing.JComboBox();
        Generatebttn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromdate_text = new javax.swing.JTextField();
        fromdate_buttn = new javax.swing.JButton();

        todate_buttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        todate_buttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todate_buttnActionPerformed(evt);
            }
        });

        location1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                location1ItemStateChanged(evt);
            }
        });

        Generatebttn.setText("Generate");
        Generatebttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneratebttnActionPerformed(evt);
            }
        });

        jLabel8.setText(AppLocal.getIntString("label.warehouse")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(133, 3, 3));
        jLabel1.setText("Consolidated Stock Report ");

        jLabel3.setText("To :");

        jLabel4.setText("From  : ");

        fromdate_buttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        fromdate_buttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromdate_buttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(location1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(toDate_text)
                            .addComponent(fromdate_text, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(todate_buttn)
                            .addComponent(fromdate_buttn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 336, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Generatebttn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(fromdate_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(fromdate_buttn))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(toDate_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(todate_buttn))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(location1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(Generatebttn)
                .addGap(58, 58, 58))
        );

        toDate_text.setEditable(false);
        fromdate_text.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void todate_buttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todate_buttnActionPerformed
       Date date;
        try {
            date = (Date) Formats.TIMESTAMP.parseValue(toDate_text.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendarTimeHours(this, date);
        if (date != null) {
            toDate_text.setText(Formats.TIMESTAMP.formatValue(date));
        }
}//GEN-LAST:event_todate_buttnActionPerformed

    private void location1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_location1ItemStateChanged
        // TODO add your handling code here:
        try {
            if (location1.getSelectedIndex() != -1) {
                LocationInfo linfo = (LocationInfo) m_LocationsModel.getSelectedItem();
                location = linfo.getID();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
}//GEN-LAST:event_location1ItemStateChanged
    Date FromDate = null;
    Date ToDate=null;
    private void GeneratebttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneratebttnActionPerformed
      if(fromdate_text.getText()!=null && fromdate_text.getText().trim().length()>0){
          if(toDate_text.getText()!=null && toDate_text.getText().trim().length()>0){
        
                try {
                    
                       FromDate = getDate(fromdate_text.getText());
                       ToDate = getDate(toDate_text.getText());
                    
                  
                        generateReport(FromDate , ToDate , location);
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }
        
        
        
        
          }
          else{
               JOptionPane.showMessageDialog(this, "Select To date ","incomplte form", JOptionPane.WARNING_MESSAGE);
          }
      }
      else{
           JOptionPane.showMessageDialog(this, "Select From Date", "incomplte form", JOptionPane.WARNING_MESSAGE);
      }
        
        
}//GEN-LAST:event_GeneratebttnActionPerformed

    private void fromdate_buttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromdate_buttnActionPerformed
         Date date;
        try {
            date = (Date) Formats.TIMESTAMP.parseValue(fromdate_text.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendarTimeHours(this, date);
        if (date != null) {
            fromdate_text.setText(Formats.TIMESTAMP.formatValue(date));
        }
    }//GEN-LAST:event_fromdate_buttnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Generatebttn;
    private javax.swing.JButton fromdate_buttn;
    private javax.swing.JTextField fromdate_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox location1;
    private javax.swing.JTextField toDate_text;
    private javax.swing.JButton todate_buttn;
    // End of variables declaration//GEN-END:variables

    
    

    public String getTitle() {
        return "ConsolidateStockDiary";
    }

    public void activate() throws BasicException {        
        toDate_text.setText(null);       
      
        m_sentlocations = dlSales.getLocationsList();
        m_LocationsModel = new ComboBoxValModel(m_sentlocations.list());
        location1.setModel(m_LocationsModel);
        Generatebttn.setText("Execute Report");

    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }

    public void init(AppView app) throws BeanFactoryException {
        dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
        m_LocationsModel = new ComboBoxValModel();
        m_App = app;
    }

    public Object getBean() {
        return this;
    }

    private Date getDate(String date) throws BasicException {
        Date d = (Date) Formats.TIMESTAMP.parseValue(date);
        Calendar cal = Calendar.getInstance();
        cal.setTimeInMillis(d.getTime());
        d.setTime(cal.getTimeInMillis());
        return d;
    }

    public void generateReport(Date FromDate , Date toDate, String location) throws BasicException {
        cmodel = new ConsolidateStockModel();
        Object[] values = new Object[]{location,FromDate,toDate};
        cmodel = cmodel.loadInstance(m_App, values);
        launch(cmodel.getConsolidate());

    }
    
    private void launch(List<ConsolidateStockReport> list) throws BasicException {
        Map reportparams = new HashMap();
        reportparams.put("companyName", m_App.getSession().getCompanyName());
        reportparams.put("companyAddress", m_App.getSession().getCompanyAddress());
        //reportparams.put("startdate", getDate(startdatetxt.getText()));
        String CurrDate = Formats.TIMESTAMP.formatValue(new Date());
        reportparams.put("enddate",CurrDate);
        String Header = "From : "+fromdate_text.getText()+ "  To : "+toDate_text.getText()+".";
        String Warehouse= "Warehouse :  "+location1.getSelectedItem().toString();
        reportparams.put("Header",Header);
        reportparams.put("Warehouse",Warehouse);
        
        
        DataSourceProvider data1 = new DataSourceProvider(list);
        DataSourceForConsolidateStock ds = new DataSourceForConsolidateStock(list);
        data1.setDataSource(ds);
        JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/consolidatestock.jrxml", reportparams, false, data1, true, null);

    }

  }   
