/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.openbravo.pos.inventory;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.SentenceList;
import com.openbravo.data.loader.SerializerReadString;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.pos.clubmang.DataSourceProvider;
import com.openbravo.pos.clubmang.JasperReportNew;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.JPanelView;
import com.openbravo.pos.panels.MemberListReport;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author dev1
 */
public class WarehousewiseReport extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {
    private AppView m_app;
    private ComboBoxValModel location_Model;
     //private SentenceList m_sentloc;
    /// private DataLogicSales dlSales; 
   private List mlist;
    private MultitaxWarehousewiseList Member_List_Report;
   private List<MultitaxWarehousewiseList.WarehouseGetSetMethod> W_wise_List;
    
    /** Creates new form WarehousewiseReport */
    public WarehousewiseReport() {
        initComponents();
        
           
           /*m_dlSales = (DataLogicSales) m_App.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
            
           m_sentloc = m_dlSales.getLocationsList();
           location_Model = new ComboBoxValModel();DataLogicSales dlSales,DirtyManager dirty,AppView app
            jComboBox1.addActionListener(dirty);*/
        
            
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Warehouse:");

        jButton1.setText("Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(74, 74, 74)
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(32, 32, 32)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
      

//------------------------
     /*   SELECT @rownum:=@rownum+1 ‘ROWNO’,
  C.NAME AS CNAME,
CASE
WHEN P.BASIC2=0 AND P.BASIC3=0 THEN CONCAT(P.NAME ,'(C)') 
WHEN P.BASIC2=0 AND P.BASIC3=1 THEN CONCAT(P.NAME ,'(C)') 
WHEN P.BASIC2=1 AND P.BASIC3=0 THEN CONCAT(P.NAME ,'(C)') 
 ELSE P.NAME END AS NAME,
   P.NAME,
   P.REFERENCE,
   COALESCE(T1.name, ' ') as tax1,
   COALESCE(T2.name, ' ') as tax2,
   COALESCE(T3.name, ' ') as tax3,
   COALESCE(T11.RATE, ' ') as rate1,
    COALESCE(T22.RATE, ' ') as rate2,
    COALESCE(T33.RATE, ' ') as rate3,
   
       TRUNCATE(PRICESELL,2),
  CASE
     
WHEN P.BASIC2=0 AND P.BASIC3=0 THEN TRUNCATE( (COALESCE(T33.RATE, ' ') *(COALESCE(T22.RATE, ' ') *(COALESCE(T11.RATE, ' ') * PRICESELL+PRICESELL)+(COALESCE(T11.RATE, ' ') * PRICESELL+PRICESELL))+(COALESCE(T22.RATE, ' ') *(COALESCE(T11.RATE, ' ') * PRICESELL+PRICESELL)+(COALESCE(T11.RATE, ' ') * PRICESELL+PRICESELL))) ,2) 
WHEN P.BASIC2=1 AND P.BASIC3=0 THEN TRUNCATE( (COALESCE(T33.RATE, ' ') *((COALESCE(T11.RATE, ' ') * PRICESELL)+(COALESCE(T22.RATE, ' ') * PRICESELL)+PRICESELL))+((COALESCE(T11.RATE, ' ') * PRICESELL)+(COALESCE(T22.RATE, ' ') * PRICESELL)+PRICESELL),2)
WHEN P.BASIC2=0 AND P.BASIC3=1 THEN TRUNCATE( (COALESCE(T22.RATE, ' ') *((COALESCE(T11.RATE, ' ') * PRICESELL)+(COALESCE(T33.RATE, ' ') * PRICESELL)+PRICESELL))+((COALESCE(T11.RATE, ' ') * PRICESELL)+(COALESCE(T33.RATE, ' ') * PRICESELL)+PRICESELL),2) ELSE   TRUNCATE((COALESCE(T11.RATE, ' ') * PRICESELL + COALESCE(T22.RATE, ' ') * PRICESELL + COALESCE(T33.RATE, ' ') * PRICESELL) + PRICESELL,
        2)   END AS TOTAL,P.BASIC2,P.BASIC3

from
    products P 
        LEFT JOIN
    taxcategories T1 ON (T1.ID = P.TAXCAT)
        LEFT JOIN
    taxcategories T2 ON (T2.ID = P.TAXCAT2)
        LEFT JOIN
    taxcategories T3 ON (T3.ID = P.TAXCAT3)
        LEFT JOIN
    taxes T11 ON (T11.CATEGORY = P.TAXCAT)
        LEFT JOIN
    taxes T22 ON (T22.CATEGORY = P.TAXCAT2)
        LEFT JOIN
    taxes T33 ON (T33.CATEGORY = P.TAXCAT3)
        LEFT JOIN
    CATEGORIES C ON ( C.ID=P.CATEGORY ),
    LOCATIONS L,
    (SELECT @rownum:=0) r
   
WHERE
    P.LOCATION = L.ID 
         AND L.NAME = ?
  GROUP BY C.ID,P.NAME

ORDER BY C.name,P.NAME*/
//------------------------        
        
        if(jComboBox1.getSelectedItem()!=null)
        {
          String memty=jComboBox1.getSelectedItem().toString();  
                  W_wise_List = new ArrayList<MultitaxWarehousewiseList. WarehouseGetSetMethod>();
                 
                  try{
                             Member_List_Report = MultitaxWarehousewiseList. LoadAll_Perticular_Type(m_app,memty);
                             }
                             
                             catch (BasicException ex) {
                                 Logger.getLogger(WarehousewiseReport.class.getName()).log(Level.SEVERE, null, ex);
                            }
                   
                   W_wise_List  =  (List<MultitaxWarehousewiseList.WarehouseGetSetMethod>) Member_List_Report. getMemberList();
                  
                  DataSourceProvider data1 = new DataSourceProvider(W_wise_List);
                  DataSourceForMultitaxWarehouseList dsfc = new DataSourceForMultitaxWarehouseList(W_wise_List);
                  data1.setDataSource(dsfc);
                   
                  Map reportparams = new HashMap();
                    
                   reportparams.put("WarehouseName",jComboBox1.getSelectedItem().toString());
                   JasperPrint jp = JasperReportNew.runReport(m_app, "./reports/com/openbravo/reports/MultitaxWarehousewiseReport.jrxml", reportparams, false, data1, true, null);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
         return "Sale Catalog Incl Tax";    }

    @Override
    public void activate() throws BasicException {
        // SentenceList mlist4=dlSales.getLocationsList();
       mlist=   new StaticSentence(m_app.getSession(), "SELECT NAME FROM  LOCATIONS  WHERE STOCK=TRUE ORDER BY NAME ", 
                             null,
                             SerializerReadString.INSTANCE).list();
         location_Model=new ComboBoxValModel( mlist);
         jComboBox1.setModel(location_Model);
    }

    @Override
    public boolean deactivate() {
                 return true;  
    }

    @Override
    public JComponent getComponent() {
           return this;
    }

    @Override
    public void init(AppView app) throws BeanFactoryException {
        m_app = app; 
        //dlSales = (DataLogicSales) m_app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
    }

    @Override
    public Object getBean() {
     return this;    
    }

   
   }
