/*
 * ReceiptPrinting.java
 *
 * Created on January 28, 2012, 12:27 PM
 */
package com.openbravo.pos.reports;

import com.openbravo.basic.BasicException;

import com.openbravo.pos.clubmang.DataLogicFacilities;
import com.openbravo.pos.clubmang.DataSourceProvider;
import com.openbravo.pos.clubmang.JasperReportNew;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.JPanelView;
import com.openbravo.pos.reports.DataSourceReceipt;

import com.openbravo.pos.reports.ReceiptDetailModel;
import com.openbravo.pos.reports.ReceiptDetailModel.ReceiptDetailModelLine;
//import com.openbravo.pos.reports.ReceiptDetailModel.ReceiptDetailModelLine1;
import com.openbravo.pos.reports.ReceiptDetailModel.ReceiptGuest;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author  user
 */
public class ReceiptPrinting extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {

    private String rptNo;
    private ReceiptDetailModel rmodel;
    private AppView m_App;
    private DataLogicSales dlsales;
    private DataLogicFacilities dlfac;

    /** Creates new form ReceiptPrinting */
    public ReceiptPrinting() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrint = new javax.swing.JButton();
        rNotxt = new javax.swing.JTextField();
        rNolbl = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        rNolbl.setText("Receipt No");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sales", "Guest Charges", "General", "Members", "Guest Charges MK" }));

        jLabel1.setText("Types of Receipt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rNolbl)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrint)
                    .addComponent(rNotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNolbl)
                    .addComponent(rNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrint)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        try {
            if (rNotxt.getText().length() > 0) {
                generateReport1(rNotxt.getText().toString());
            } else {
                JOptionPane.showMessageDialog(this, "Enter receipt number", "incomplte form", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnPrintActionPerformed

    public void generateReport1(String id) throws BasicException {
        rmodel = new ReceiptDetailModel();
        if (jComboBox1.getSelectedIndex() == 0) {
            rmodel = rmodel.loadInstance(m_App, id);
            launch(rmodel.getReceiptlist());
        } else if (jComboBox1.getSelectedIndex() == 1) {
            rmodel = rmodel.loadInstanceguest(m_App, id);
            launchguest(rmodel.getRptlist1());
        } else if (jComboBox1.getSelectedIndex() == 2) {
            rmodel = rmodel.loadInstancegeneral(m_App, id);
            launchgeneral(rmodel.getRecgen());
        } else if (jComboBox1.getSelectedIndex() == 3){
             rmodel = rmodel.loadInstancemember(m_App, id);
            launchmember(rmodel.getRecmem());
        }
        else if (jComboBox1.getSelectedIndex() == 4){
             rmodel = rmodel.loadInstanceguestMK(m_App, id);
            launchguestMK(rmodel.getRptlist1());
        }

    }

    private void launch(List<ReceiptDetailModelLine> receiptlist) {
        try {
            Map reportparams = new HashMap();
            reportparams.put("comname", m_App.getSession().getCompanyName());
            reportparams.put("comaddr", m_App.getSession().getCompanyAddress());
            reportparams.put("receiptnor", rNotxt.getText().toUpperCase());
              reportparams.put("createdby", rmodel.getCreatedby());
               reportparams.put("chequeno", rmodel.getChequeno());
                reportparams.put("bank", rmodel.getBank());
            
            // reportparams.put("Date", );
            if (jComboBox1.getSelectedIndex() == 0) {
                DataSourceProvider data = new DataSourceProvider(receiptlist);
                DataSourceReceipt ds = new DataSourceReceipt(receiptlist);
                data.setDataSource(ds);
                JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/dupreceipt.jrxml", reportparams, false, data, true, null);
            } 
            activate();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    
    
     private void launchguest(List<ReceiptGuest> receiptlist) {
        try {
            Map reportparams = new HashMap();
            reportparams.put("comname", m_App.getSession().getCompanyName());
            reportparams.put("comaddr", m_App.getSession().getCompanyAddress());
            reportparams.put("receiptnor", rNotxt.getText().toUpperCase());
                reportparams.put("chequeno", rmodel.getChequeno());
                 reportparams.put("bank", rmodel.getBank());
            if (jComboBox1.getSelectedIndex() == 1) {
                DataSourceProvider data = new DataSourceProvider(receiptlist);
                DataSourceReceiptGuest ds = new DataSourceReceiptGuest(receiptlist);
                data.setDataSource(ds);
                JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/dupreceiptguest.jrxml", reportparams, false, data, true, null);
            } 
            activate();
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }
    
      private void launchguestMK(List<ReceiptGuest> receiptlist) {
        try {
            Map reportparams = new HashMap();
            reportparams.put("comname", m_App.getSession().getCompanyName());
            reportparams.put("comaddr", m_App.getSession().getCompanyAddress());
            reportparams.put("receiptnor", rNotxt.getText().toUpperCase());
               // reportparams.put("chequeno", rmodel.getChequeno());
                // reportparams.put("bank", rmodel.getBank());
            if (jComboBox1.getSelectedIndex() == 4) {
                DataSourceProvider data = new DataSourceProvider(receiptlist);
                DataSourceReceiptGuest ds = new DataSourceReceiptGuest(receiptlist);
                data.setDataSource(ds);
                JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/dupreceiptguest.jrxml", reportparams, false, data, true, null);
            } 
            activate();
        } catch (Exception e) {
            e.printStackTrace();
        }
       
    }
    
      
        private void launchgeneral(List<ReceiptDetailModel.ReceiptGeneral> receiptlist) {
        try {
             Map reportparams = new HashMap();
            reportparams.put("comname", m_App.getSession().getCompanyName());
            reportparams.put("comaddr", m_App.getSession().getCompanyAddress());
            reportparams.put("receiptnor", rNotxt.getText().toUpperCase());
            reportparams.put("narration", rmodel.getNarration());
            reportparams.put("paymentmode", rmodel.getPaymentmode());
            reportparams.put("crdate", rmodel.getCrdate());
            reportparams.put("customer", rmodel.getCustomer());
            reportparams.put("createdby", rmodel.getCreatedby());
            reportparams.put("role", rmodel.getRole());
            reportparams.put("chequeno", rmodel.getChequeno());
             reportparams.put("bank", rmodel.getBank());
            if (jComboBox1.getSelectedIndex() == 2) {
                DataSourceProvider data = new DataSourceProvider(receiptlist);
                DataSourceReceiptGeneral ds = new DataSourceReceiptGeneral(receiptlist);
                data.setDataSource(ds);
                JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/dupreceiptgeneral.jrxml", reportparams, false, data, true, null);

            }
            activate();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
     private void launchmember(List<ReceiptDetailModel.ReceiptMember> receiptlist) {
          try {
            Map reportparams = new HashMap();
            reportparams.put("comname", m_App.getSession().getCompanyName());
            reportparams.put("comaddr", m_App.getSession().getCompanyAddress());
            reportparams.put("receiptnor", rNotxt.getText().toUpperCase());
            reportparams.put("fname", rmodel.getFname());
             reportparams.put("amount", rmodel.getAmount());
            
           reportparams.put("chequeno", rmodel.getChequeno());
            reportparams.put("bank", rmodel.getBank());
            if (jComboBox1.getSelectedIndex() == 3) {
               DataSourceProvider data = new DataSourceProvider(receiptlist);
              DataSourceReceiptMember ds = new DataSourceReceiptMember(receiptlist);
              data.setDataSource(ds);
              JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/dupreceiptmember.jrxml", reportparams, false, data, true, null);
        } 
          activate();
          }catch (Exception e) {
            e.printStackTrace();
        }
     }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rNolbl;
    private javax.swing.JTextField rNotxt;
    // End of variables declaration//GEN-END:variables
    public String getTitle() {
        return "ReceiptPrint";
    }

    public void activate() throws BasicException {
        //rNolbl.setVisible(false);
        //rNotxt.setVisible(false);
        // btnPrint.setVisible(false);
        rNotxt.setText(null);
    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }

    public void init(AppView app) throws BeanFactoryException {
        m_App = app;
        dlsales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
    }

    public Object getBean() {
        return this;
    }
}
   

