package com.openbravo.pos.sales.restaurant;


import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.sales.QTicketLineInfo;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import com.openbravo.data.loader.DataRead;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.PreparedSentence;
import com.openbravo.data.loader.SerializableRead;
import com.openbravo.data.loader.SerializerWriteBasic;
import javax.swing.JOptionPane;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * discountdetail.java
 *
 * Created on Jan 9, 2009, 1:18:31 PM
 */

/**
 *
 * @author swathi
 */
public class reasondetail extends javax.swing.JDialog {

    /** Creates new form discountdetail */
    QTicketLineInfo qtline;
    DataLogicSales dlsales;
    public boolean resultok=false;
    private AppView app;    
    private int limit;
    private Object[] obj;
  //  public discountDetail de=new discountDetail();



    protected reasondetail(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public  reasondetail(Frame parent,AppView app)
    {
        super(parent,true);
         this.app=app;         
         initComponents();
    }
     public  reasondetail(Dialog parent,AppView app)
    {
        super(parent,true);
        this.app=app;       
        initComponents();
    }
    protected reasondetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
      protected static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window)parent;
        } else {
            return getWindow(parent.getParent());
        }
    }


    public static reasondetail getDialog(Component parent,AppView app) {

        Window window = getWindow(parent);

       reasondetail dP;

        if (window instanceof Frame) {
            dP = new reasondetail((Frame) window,app);
        } else {
            dP = new reasondetail((Dialog) window,app);
        }

        return dP;
    }

    public  boolean showDialog(Object[] val) throws BasicException {
           this.obj = val;
          jTextArea1.setEditable(true);
          jTextArea1.setText(null);
          jButton1.setEnabled(true);         
          this.setVisible(true);
          return resultok;
          
    }
    public static class detail implements SerializableRead
    {
        private  String name;
        private int qty;
         public void readValues(DataRead dr) throws BasicException {
           name = dr.getString(1);
           qty = dr.getInt(2);
        }
        public String getname()
        {
            return name;
        }
        public int getqty()
        {
            return qty;
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Reason         :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            //  dispose();
            if(jTextArea1.getText().length()>0){
            Object[] values = null;
            if(obj!=null){
               values = new Object[]{obj[0],obj[1],obj[2],obj[3],obj[4],jTextArea1.getText()};
            }
            new PreparedSentence(app.getSession(), "INSERT INTO FACILITYLIMITAPPROVAL(ID,MEMID,FACID,RDATE,AMOUNTREACH,INITREASON) VALUES(?,?,?,?,?,?)", new SerializerWriteBasic(new Datas[]{Datas.STRING, Datas.STRING, Datas.STRING, Datas.TIMESTAMP, Datas.DOUBLE,Datas.STRING})).exec(values);
            dispose();
            JOptionPane.showMessageDialog(this, "request sent  for approval");
            }
            else{
                JOptionPane.showMessageDialog(this, "give reason....");
            }
        } catch (BasicException ex) {
            ex.printStackTrace();
        }
          

        
    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
    * @param args the command line arguments
    */
 /*   public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                discountdetail dialog = new discountdetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
