/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelCloseSaleTable.java
 *
 * Created on 30-May-2011, 10:23:37
 */
package com.openbravo.pos.panels;

import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SerializerReadBasic;
import com.openbravo.data.loader.SerializerWriteString;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.format.Formats;
import com.openbravo.pos.clubmang.AllRoles;
import com.openbravo.pos.clubmang.DataLogicFacilities;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.JPanelView;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.ListSelectionModel;
import com.openbravo.pos.clubmang.DataSourceProvider;
import com.openbravo.pos.clubmang.JRBasicField;
import com.openbravo.pos.clubmang.JasperReportNew;

import com.openbravo.pos.inventory.DataSourceForConsolidateStock;
import com.openbravo.pos.panels.CloseSaleTableModel.saleList;
import com.openbravo.pos.util.JRViewer300;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRField;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author swathi
 */
public class JPanelCloseSaleTable extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {

    private AppView m_App;
    private CloseSaleTableModel dbmodel;
     private CloseSaleTableModel dbmodel1;
   //  private CloseSaleTableModel dbmodel2;
     private CloseSaleTableModel dbmodel3 = null;
    private saleList sale;
    private ComboBoxValModel rmodel;
    private DataLogicFacilities dlfac;
    Date fdate;
    Date todate;
    private String companyName = null;
    private String companyAddress = null;
    private String s = null;
    private JRViewer300 reportviewer = null;
    private Double saleListTotal = null;
    private Double closeSaleTotal = null;
    private String sequence = null;
    private Date subFdate = null;
    private Date subTodate = null;
    private ConsolidateStockCloseSaleModel cmodel;

    /** Creates new form JPanelCloseSaleTable */
    public JPanelCloseSaleTable() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        fromDate_text = new javax.swing.JTextField();
        toDate_text = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        roles = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        DetailedProdReport_Button = new javax.swing.JButton();

        jDialog1.setName("jDialog1"); // NOI18N

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jDialog2.setName("jDialog2"); // NOI18N

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        fromDate_text.setName("fromDate_text"); // NOI18N

        toDate_text.setName("toDate_text"); // NOI18N

        jLabel1.setText("From");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("To");
        jLabel2.setName("jLabel2"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Roles");
        jLabel3.setName("jLabel3"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table1.setName("table1"); // NOI18N
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);

        jButton3.setText("Print");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        roles.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roles.setName("roles"); // NOI18N
        roles.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rolesItemStateChanged(evt);
            }
        });
        roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolesActionPerformed(evt);
            }
        });

        jButton4.setText("Execute");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("back");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Print Product");
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table2.setName("table2"); // NOI18N
        jScrollPane2.setViewportView(table2);

        jButton7.setText("Print Bill");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        DetailedProdReport_Button.setText("Detailed Product Report");
        DetailedProdReport_Button.setName("DetailedProdReport_Button"); // NOI18N
        DetailedProdReport_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailedProdReport_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(toDate_text)
                                            .addComponent(fromDate_text, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton1)
                                            .addComponent(jButton2)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jButton4))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(DetailedProdReport_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(750, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fromDate_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(toDate_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton7)
                    .addComponent(DetailedProdReport_Button))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date date1;
        try {
            date1 = (Date) Formats.DATE.parseValue(fromDate_text.getText());
        } catch (BasicException e) {
            date1 = null;
        }
        date1 = JCalendarDialog.showCalendar(this, date1);
        if (date1 != null) {
            fromDate_text.setText(Formats.DATE.formatValue(date1));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date date1;
        try {
            date1 = (Date) Formats.DATE.parseValue(toDate_text.getText());
        } catch (BasicException e) {
            date1 = null;
        }
        date1 = JCalendarDialog.showCalendar(this, date1);
        if (date1 != null) {
            toDate_text.setText(Formats.DATE.formatValue(date1));
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private JRField[] getFields() throws JRException, UnsupportedOperationException {
        JRField[] fields = new JRField[12];
        fields[0] = (JRField) new JRBasicField("sequence", "seq", java.lang.String.class, "java.lang.String");
        fields[1] = (JRField) new JRBasicField("dateStart", "sdate", java.util.Date.class, "java.util.Date");
        fields[2] = (JRField) new JRBasicField("dateEnd", "edate", java.util.Date.class, "java.util.Date");
        fields[3] = (JRField) new JRBasicField("Amount", "amount", java.lang.Double.class, "java.lang.Double");
        fields[4] = (JRField) new JRBasicField("roleName", "role", java.lang.String.class, "java.lang.String");
        fields[5] = (JRField) new JRBasicField("Amount1", "amt", java.lang.Double.class, "java.lang.Double");
        fields[6] = (JRField) new JRBasicField("billno", "billno", java.lang.String.class, "java.lang.String");
        fields[7] = (JRField) new JRBasicField("date", "date", java.util.Date.class, "java.util.Date");
        fields[8] = (JRField) new JRBasicField("memno", "memno", java.lang.String.class, "java.lang.String");
        fields[9] = (JRField) new JRBasicField("memname", "memname", java.lang.String.class, "java.lang.String");
        return fields;
    }
    
    
     private JRField[] getFields1() throws JRException, UnsupportedOperationException {
        JRField[] fields = new JRField[6];
        fields[0] = (JRField) new JRBasicField("Qty", "Qty", java.lang.String.class, "java.lang.Double");
      //  fields[1] = (JRField) new JRBasicField("dateStart", "sdate", java.util.Date.class, "java.util.Date");
     //  fields[2] = (JRField) new JRBasicField("dateEnd", "edate", java.util.Date.class, "java.util.Date");
      //  fields[3] = (JRField) new JRBasicField("Amount", "amount", java.lang.Double.class, "java.lang.Double");
        fields[1] = (JRField) new JRBasicField("Rate", "Rate", java.lang.String.class, "java.lang.Double");
        //fields[5] = (JRField) new JRBasicField("Amount1", "amt", java.lang.Double.class, "java.lang.Double");
        fields[2] = (JRField) new JRBasicField("ProductName", "ProductName", java.lang.String.class, "java.lang.String");
//        fields[7] = (JRField) new JRBasicField("date", "date", java.util.Date.class, "java.util.Date");
//        fields[8] = (JRField) new JRBasicField("memno", "memno", java.lang.String.class, "java.lang.String");
//        fields[9] = (JRField) new JRBasicField("memname", "memname", java.lang.String.class, "java.lang.String");
//         fields[3] = (JRField) new JRBasicField("fromDate", "sdate", java.util.Date.class, "java.util.Date");
//        fields[4] = (JRField) new JRBasicField("toDate", "edate", java.util.Date.class, "java.util.Date");
//          fields[5] = (JRField) new JRBasicField("Date", "Date", java.util.Date.class, "java.util.Date");
     fields[3] = (JRField) new JRBasicField("date", "date", java.util.Date.class, "java.util.Date");
       
        
        
        return fields;
    }

    
    
    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            closeSaleTotal = dbmodel.getTotalAmountOfCloseSaleLine();
            companyName = m_App.getSession().getCompanyName();
            companyAddress = m_App.getSession().getCompanyAddress();
            Map reportparams = new HashMap();
            reportparams.put("fromDate", fdate);
            reportparams.put("toDate", todate);
            reportparams.put("companyName", companyName);
            reportparams.put("companyAddress", companyAddress);
            reportparams.put("total", closeSaleTotal);
            DataSourceProvider data1 = new DataSourceProvider(dbmodel.getCloseSaleLine());
            data1.setFields(getFields());
            ClosedSaleDataSource ds = new ClosedSaleDataSource(dbmodel.getCloseSaleLine());
            data1.setDataSource(ds);
            reportparams.put("closedsaledatasource", ds);
            
            JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/ClosedSaleReport.jrxml", reportparams, false, data1, true, null);


        } catch (Exception ex) {
            ex.printStackTrace();
        }



    }//GEN-LAST:event_jButton3ActionPerformed

    private void rolesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rolesItemStateChanged
    // TODO add your handling code here:
    }//GEN-LAST:event_rolesItemStateChanged
    String RoleID=null;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (fromDate_text.getText().length() > 0 && toDate_text.getText().length() > 0 && roles.getSelectedItem() != null) {
            try {
                jButton5.setVisible(false);
                jButton6.setVisible(false);
                DetailedProdReport_Button.setVisible(false);
                jButton7.setVisible(false);
                if (fromDate_text.getText().isEmpty() == true && toDate_text.getText().isEmpty() == true) {
                    JOptionPane.showMessageDialog(this, "Please Enter both start an end date");
                } else if (fromDate_text.getText().isEmpty() == true) {
                    JOptionPane.showMessageDialog(this, "Please Enter Start Date");
                } else if (toDate_text.getText().isEmpty() == true) {
                    JOptionPane.showMessageDialog(this, "Please Enter End Date");
                } else if (fromDate_text.getText().isEmpty() == false && toDate_text.getText().isEmpty() == false) {
                    fdate = (Date) Formats.DATE.parseValue(fromDate_text.getText());
                    todate = (Date) Formats.DATE.parseValue(toDate_text.getText());
                    Calendar cal1 = Calendar.getInstance();
                    Calendar cal2 = Calendar.getInstance();
                    cal1.setTime(fdate);
                    cal1.set(Calendar.HOUR_OF_DAY, 00);
                    cal1.set(Calendar.MINUTE, 00);
                    cal1.set(Calendar.SECOND, 00);
                    cal1.set(Calendar.MILLISECOND, 00);
                    cal2.setTime(todate);
                    cal2.set(Calendar.HOUR_OF_DAY, 59);
                    cal2.set(Calendar.MINUTE, 59);
                    cal2.set(Calendar.SECOND, 59);
                    cal2.set(Calendar.MILLISECOND, 59);
                    AllRoles role = (AllRoles) roles.getSelectedItem();
                    s = role.getName();
                    RoleID=role.getId();
                    
                    System.out.println(s);
                    dbmodel = CloseSaleTableModel.loadInstantce(m_App, cal1.getTime(), cal2.getTime(), s);
                    dbmodel3 = CloseSaleTableModel.loadInstantce(m_App, cal1.getTime(), cal2.getTime(), s);
                    table1.setModel(dbmodel.getTableModel());
                    int i = dbmodel.getTableModel().getRowCount();
                    jButton3.setVisible(true);
                    table1.addMouseListener(new java.awt.event.MouseAdapter() {

                        @Override
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            //TableMouseClicked(evt);
                        }
                    });
                }

            } catch (BasicException ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "fill the form completely", "incomplete form", JOptionPane.WARNING_MESSAGE);

        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            fdate = (Date) Formats.DATE.parseValue(fromDate_text.getText());
            todate = (Date) Formats.DATE.parseValue(toDate_text.getText());
            dbmodel = CloseSaleTableModel.loadInstantce(m_App, fdate, todate, s);
            table1.setModel(dbmodel.getTableModel());
            dbmodel1 = CloseSaleTableModel.emptyinstance();
             table2.setModel(dbmodel1.getTableModel());
            
            int i = dbmodel.getTableModel().getRowCount();
            jButton3.setVisible(true);
            jButton6.setVisible(false);
            DetailedProdReport_Button.setVisible(false);
            jButton5.setVisible(false);
        } catch (BasicException ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code her  e:
        try {
            Double total = 0.00;
           // dbmodel = CloseSaleTableModel.loadInstantce(m_App, cal1.getTime(), cal2.getTime(), s);
            closeSaleTotal = dbmodel3.getTotalAmountOfCloseSaleLine();
            closeSaleTotal = 0.00;
            List<CloseSaleTableModel.ProdList> pl = dbmodel1.getProdDetails();
            for (Iterator<CloseSaleTableModel.ProdList> it = pl.iterator(); it.hasNext();) {
                CloseSaleTableModel.ProdList prodList = it.next();
                {
                   total = total+prodList.getRate(); 
                }
                
            }
             
            companyName = m_App.getSession().getCompanyName();
            companyAddress = m_App.getSession().getCompanyAddress();
            Map reportparams = new HashMap();
            reportparams.put("fromDate", subFdate);
            reportparams.put("toDate", subTodate);
            reportparams.put("companyName", companyName);
            reportparams.put("companyAddress", companyAddress);
            reportparams.put("Total", total);
            reportparams.put("seq", sequence);
            DataSourceProvider data2 = new DataSourceProvider(dbmodel1.getProdDetails());
            data2.setFields(getFields1());
            ClosedSaleDataSource1new ds1 = new ClosedSaleDataSource1new(dbmodel1.getProdDetails());
            data2.setDataSource(ds1);
            reportparams.put("closedsaledatasource1", ds1);
            
            
            
            
//            Map reportparams = new HashMap();
//            reportparams.put("fromDate", fdate);
//            reportparams.put("toDate", todate);
//            reportparams.put("companyName", companyName);
//            reportparams.put("companyAddress", companyAddress);
//           // reportparams.put("Total", saleListTotal);
//           /// System.out.println(saleListTotal);
           // DataSourceProvider data2 = new DataSourceProvider(dbmodel1.getProdDetails());
//            data2.setFields(getFields());
//            ClosedSaleDataSource1new ds1 = new  ClosedSaleDataSource1new(dbmodel1.getProdDetails());
//            System.out.println(ds1);
//           // data2.setDataSource(ds1);
//            reportparams.put("closedsaledatasource1", ds1);
//            DataSourceProvider data2 = new DataSourceProvider(dbmodel1.getProdDetails());
//            data2.setFields(getFields());
//            CloseSaleProdSource ds1 = new CloseSaleProdSource(dbmodel1.getProdDetails());
//
//            data2.setDataSource(ds1);
//            reportparams.put("CloseSaleProdSource", ds1);
            
            JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/ClosedSaleProdReport1.jrxml", reportparams, false, data2, true, null);
        //reportviewer.loadJasperPrint(jp);
             //  JasperPrint jp1 = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/CloseSaleProdReport.jrxml", reportparams, false, data2, true, null);
        } catch (Exception ex) {
            ex.printStackTrace();
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesActionPerformed
    // TODO add your handling code here:
        
    }//GEN-LAST:event_rolesActionPerformed

private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked

    try {
            int row = 0;
            if (evt.getClickCount() == 2) {
                if (jScrollPane1.getViewport().getView() instanceof JTable) {
                    row = table1.getSelectedRow();
                }
                DateFormat df = new SimpleDateFormat("dd MMM,yyyy");
                fdate = df.parse(fromDate_text.getText().toString());
                todate = df.parse(toDate_text.getText().toString());
                Calendar cal1 = Calendar.getInstance();
                Calendar cal2 = Calendar.getInstance();
                cal1.setTime(fdate);
                cal1.set(Calendar.HOUR_OF_DAY, 00);
                cal1.set(Calendar.MINUTE, 00);
                cal1.set(Calendar.SECOND, 00);
                cal1.set(Calendar.MILLISECOND, 00);
                cal2.setTime(todate);
                cal2.set(Calendar.HOUR_OF_DAY, 23);
                cal2.set(Calendar.MINUTE, 59);
                cal2.set(Calendar.SECOND, 59);
                cal2.set(Calendar.MILLISECOND, 59);
                String role = (String) dbmodel.getTableModel().getValueAt(row, 5);
                sequence = (String) dbmodel.getTableModel().getValueAt(row, 0);
                subFdate = (Date)  dbmodel.getTableModel().getValueAt(row, 1);
                subTodate = (Date)  dbmodel.getTableModel().getValueAt(row, 2);
                String id = role + " : " + sequence;
                System.out.println(id);
                dbmodel = CloseSaleTableModel.loadInstanceOfSale(m_App, cal1.getTime(), cal2.getTime(), id);
               
                
                
                dbmodel1= CloseSaleTableModel.loadInstanceOfProd(m_App, cal1.getTime(), cal2.getTime(),sequence,role);
              //  dbmodel2 = CloseSaleTableModel.loadInstanceOfSaleProd(m_App, cal1.getTime(), cal2.getTime(),id,sequence,role);
               
                  saleListTotal = dbmodel.getTotalAmountOfSaleList();
                table1.setModel(dbmodel.getTableModel1());

                table2.setModel(dbmodel1.getTableModel2());
             //    saleListTotal = dbmodel2.getTotalAmountOfSaleList1();
                jButton3.setVisible(false);
                jButton5.setVisible(true);
                jButton6.setVisible(true);
                DetailedProdReport_Button.setVisible(true);
                jButton7.setVisible(true);
                //saleListTotal1 = dbmodel2.getTotalAmountOfSaleList1();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    
}//GEN-LAST:event_table1MouseClicked

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            List<CloseSaleTableModel.saleList> saleList = dbmodel.getsaleList();
            saleList.size();
            double total = 0;
            for (Iterator<saleList> it = saleList.iterator(); it.hasNext();) {
                saleList list = it.next();
                total = total + list.getAmount();
            }
            
            companyName = m_App.getSession().getCompanyName();
                    companyAddress = m_App.getSession().getCompanyAddress();
                    Map reportparams = new HashMap();
                    reportparams.put("fromDate", subFdate);
                    reportparams.put("toDate", subTodate);
                    reportparams.put("companyName", companyName);
                    reportparams.put("companyAddress", companyAddress);
                    reportparams.put("total", total);
                    reportparams.put("seq", sequence);
                    
                    DataSourceProvider data2 = new DataSourceProvider(dbmodel.getsaleList());
                    data2.setFields(getFields());
                    ClosedSaleDataSource1 ds1 = new ClosedSaleDataSource1(dbmodel.getsaleList());
                    data2.setDataSource(ds1);
        
                    JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/ClosedSaleBillReport1.jrxml", reportparams, false, data2, true, null);
        
        
        } catch (JRException ex) {
            Logger.getLogger(JPanelCloseSaleTable.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedOperationException ex) {
            Logger.getLogger(JPanelCloseSaleTable.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
}//GEN-LAST:event_jButton7ActionPerformed
    Date FromDate = null;
    Date ToDate=null;
    String LocationName = null;
    private void DetailedProdReport_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailedProdReport_ButtonActionPerformed
        if(fromDate_text.getText()!=null && fromDate_text.getText().trim().length()>0){
          if(toDate_text.getText()!=null && toDate_text.getText().trim().length()>0){
        
              
              
                try {
                    
                      Object[] obj1 = (Object[]) new StaticSentence(m_App.getSession(), "select prcategories from people   where role=? and visible=true LIMIT 1", SerializerWriteString.INSTANCE, new SerializerReadBasic(new Datas[]{Datas.STRING})).find(RoleID);
                      if(obj1!=null){ 
                         if(obj1[0]!=null){ 
                            String location=   obj1[0].toString();
                            Object[] obj2 = (Object[]) new StaticSentence(m_App.getSession(), "Select NAME FROM LOCATIONS WHERE ID=?", SerializerWriteString.INSTANCE, new SerializerReadBasic(new Datas[]{Datas.STRING})).find(location);
                            if(obj2!=null){
                              LocationName=obj2[0].toString();
                            }
                            //FromDate = getDate(fromDate_text.getText());
                            ToDate = getDate(toDate_text.getText());
                            FromDate=subFdate;
                             generateReport(subFdate , subTodate , location);
                        
                         }
                      }
                      else{
                          JOptionPane.showMessageDialog(this, "No warehouse found. Contact Administrator","incomplte form", JOptionPane.WARNING_MESSAGE);
                      }
                } catch (Exception e) {
                    e.printStackTrace();
                }
        
        
        
        
          }
          else{
               JOptionPane.showMessageDialog(this, "Select To date ","incomplte form", JOptionPane.WARNING_MESSAGE);
          }
      }
      else{
           JOptionPane.showMessageDialog(this, "Select From Date", "incomplte form", JOptionPane.WARNING_MESSAGE);
      }
    }//GEN-LAST:event_DetailedProdReport_ButtonActionPerformed

    
    public void generateReport(Date FromDate , Date toDate, String location) throws BasicException {
        List<CloseSaleTableModel.saleList> saleListZ = dbmodel.getsaleList();
        saleListZ.size();
        double total = 0;
        for (Iterator<saleList> it = saleListZ.iterator(); it.hasNext();) {
            saleList list = it.next();
            total = total + list.getAmount();
         }
        Double ProdTotal=0.00;
        List<CloseSaleTableModel.ProdList> pl = dbmodel1.getProdDetails();
            for (Iterator<CloseSaleTableModel.ProdList> it = pl.iterator(); it.hasNext();) {
                CloseSaleTableModel.ProdList prodList = it.next();
                {
                   ProdTotal = ProdTotal+prodList.getRate(); 
                }
                
            }
        
        
        System.out.println("Grand Total is : "+total);
        cmodel = new ConsolidateStockCloseSaleModel();
        Object[] values = new Object[]{location,FromDate,toDate};
        cmodel = cmodel.loadInstance(m_App, values);
        launch(cmodel.getConsolidate() , total , ProdTotal);
        
    }
    
    private void launch(List<ConsolidateStockCloseSaleModel.ConsolidateStockReport> list , Double  total , Double ProdTotal) throws BasicException {
        Map reportparams = new HashMap();
        reportparams.put("companyName", m_App.getSession().getCompanyName());
        reportparams.put("companyAddress", m_App.getSession().getCompanyAddress());
        //reportparams.put("startdate", getDate(startdatetxt.getText()));
        String CurrDate = Formats.TIMESTAMP.formatValue(new Date());
        reportparams.put("enddate",CurrDate);
        String Header = "From : "+Formats.TIMESTAMP.formatValue(subFdate)+ "  To : "+Formats.TIMESTAMP.formatValue(subTodate)+".";
        String Warehouse= "Warehouse :  "+LocationName;
        reportparams.put("Header",Header);
        reportparams.put("Warehouse",Warehouse);
        reportparams.put("GTOTALWITHTAX",total);
        Double Taxtotal = total-ProdTotal;
        reportparams.put("GTaxTotal",Taxtotal);
        
        DataSourceProvider data1 = new DataSourceProvider(list);
        DataSourceForConsolidateStockCloseSale ds = new DataSourceForConsolidateStockCloseSale(list , dbmodel1.getProdDetails());
        data1.setDataSource(ds);
        JasperPrint jp = JasperReportNew.runReport(m_App, "./reports/com/openbravo/reports/consolidatestockCloseSale.jrxml", reportparams, false, data1, true, null);

    }
    
    private Date getDate(String date) throws BasicException {
        Date d = (Date) Formats.TIMESTAMP.parseValue(date);
        Calendar cal = Calendar.getInstance();
        cal.setTimeInMillis(d.getTime());
        d.setTime(cal.getTimeInMillis());
        return d;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DetailedProdReport_Button;
    private javax.swing.JTextField fromDate_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox roles;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    private javax.swing.JTextField toDate_text;
    // End of variables declaration//GEN-END:variables
    public String getTitle() {
        return "CloseSaleReprint";
    }

    public void activate() throws BasicException {
        loadData();
    }

    private void loadData() throws BasicException {

        toDate_text.setText(null);
        fromDate_text.setText(null);
        dbmodel = CloseSaleTableModel.emptyinstance();
        table1.setModel(dbmodel.getTableModel());
        table2.setModel(dbmodel.getTableModel());
        //jLabel3.setVisible(false);
        //roles.setVisible(false);
        jButton5.setVisible(false);
        jButton3.setVisible(false);
        jButton6.setVisible(false);
        DetailedProdReport_Button.setVisible(false);
        jButton7.setVisible(false);
        List<AllRoles> rolelist = dlfac.getAllRoles();
        rmodel = new ComboBoxValModel(rolelist);
        roles.setModel(rmodel);


    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }

    public void init(AppView app) throws BeanFactoryException {
        m_App = app;
        table1.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        dlfac = (DataLogicFacilities) app.getBean("com.openbravo.pos.clubmang.DataLogicFacilitiesCreate");
    }

    public Object getBean() {
        return this;
    }

//    private void TableMouseClicked(java.awt.event.MouseEvent evt) {
//        
//    }
}
