/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BillNo.java
 *
 * Created on Feb 26, 2009, 5:48:37 PM
 */

package com.openbravo.pos.ticket;

import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.reports.PanelReportBean;
import com.openbravo.pos.reports.ReportEditorCreator;
import java.awt.Component;

/**
 *
 * @author swathi
 */
public class BillNo extends javax.swing.JPanel implements ReportEditorCreator {

    /** Creates new form BillNo */
     private PanelReportBean   report;
    private AppView m_App;
    public BillNo() {
        initComponents();
    }
 public void init(AppView app) {
        m_App=app;
        DataLogicSales dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");

        // El modelo de categorias

 }
   public void activate() throws BasicException {
        billnum.setText("");
   }
   public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(
                new Datas[] {Datas.OBJECT, Datas.STRING});
    }
    public Component getComponent() {
        return this;
    }

    public Object createValue() throws BasicException {
        String num=billnum.getText();
         return new Object[] {
            num.equals("") ? QBFCompareEnum.COMP_NONE : QBFCompareEnum.COMP_EQUALS,
            num
         };
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        billnum = new javax.swing.JTextField();

        jLabel1.setText("Bill No :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(billnum, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(billnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField billnum;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
