/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * currentbill.java
 *
 * Created on Dec 22, 2008, 3:39:26 PM
 */

package com.openbravo.pos.sales;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.admin.CardReader;
import com.openbravo.pos.customers.CustomerInfoExt;
import com.openbravo.pos.customers.DataLogicCustomers;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.JPanelView;
import com.openbravo.pos.sales.restaurant.BillList;
import com.openbravo.pos.sales.restaurant.DebtBillList;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComponent;

/**
 *
 * @author swathi
 */
public class CurrentBill extends javax.swing.JPanel implements JPanelView, BeanFactoryApp{

    private AppView app;
    private DataLogicSales dlSales;
    private BillLogic dlBill;
    private CustomerInfoExt customer;
    private DataLogicCustomers dlCustomers;
    private String portNumber;
    /** Creates new form currentbill */
    public CurrentBill() {
        
        initComponents();
    }

     private void displayBillList() {

       // customer = dlSales.loadCustomerExt(TOOL_TIP_TEXT_KEY)
        BillList billList = BillList.getDialog(this, dlSales, dlBill, customer);
        billList.showDialog();
    }
     private void displayCreditConfirmationList() {
        DebtBillList dbillList = DebtBillList.getDialog(this, dlSales, app,true);
        dbillList.showDialog();
    }
     


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/greenled.png"))); // NOI18N
        jButton1.setText("Cash Bill List");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Credit Confirm List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton1)
                .addGap(53, 53, 53)
                .addComponent(jButton2)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        displayBillList();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        displayCreditConfirmationList();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

     public void activate() throws BasicException {
        init(app);

    }

    public boolean deactivate() {
        return true;
    }



    @Override
     public String getTitle() {
        return AppLocal.getIntString("Menu.CurrentBills");
    }

    public Object getBean() {
        return this;
    }

      public JComponent getComponent() {
        return this;
    }

    public void init(AppView app) throws BeanFactoryException {
        this.app = app;
        dlCustomers = (DataLogicCustomers) app.getBean("com.openbravo.pos.customers.DataLogicCustomersCreate");
        dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
        this.dlBill = (BillLogic) app.getBean("com.openbravo.pos.sales.BillLogic");
        dlBill.setDataLogicSales(dlSales);
        dlBill.setAppView(app);
        jButton2.setText("<html>Pending Credit<br>Confirmation</html>");
        try {
            jButton2.setIcon(new ImageIcon(ImageIO.read(CurrentBill.class.getResourceAsStream("/com/openbravo/images/ball.png"))));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }


}
