/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BreakageDetails.java
 *
 * Created on Feb 15, 2009, 12:49:58 PM
 */

package com.openbravo.pos.panels;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.TableRendererBasic;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.DataLogicSystem;
import com.openbravo.pos.forms.JPanelView;
import java.awt.Dimension;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author swathi
 */
public class BreakageDetails extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {

    /** Creates new form BreakageDetails */
    private AppView m_App;
    private DataLogicSystem m_dlSystem;
    private DataLogicSales m_dlSales;
    private BreakageDetailTable btable;

    public BreakageDetails() {
        initComponents();
    }

    public void init(AppView app) throws BeanFactoryException {

        m_App = app;
        m_dlSystem = (DataLogicSystem) m_App.getBean("com.openbravo.pos.forms.DataLogicSystemCreate");
        m_dlSales = (DataLogicSales) m_App.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
          jTable1.setDefaultRenderer(Object.class, new TableRendererBasic(
                new Formats[] {Formats.TIMESTAMP, Formats.STRING,Formats.DOUBLE,Formats.STRING}));
       jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.getVerticalScrollBar().setPreferredSize(new Dimension(25,25));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.setRowHeight(25);
        jTable1.getSelectionModel().setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
    }

    public Object getBean() {
        return this;
    }

    public JComponent getComponent() {
        return this;
    }

   public String getTitle() {
        return "Breakage Detail";
    }

    public void activate() throws BasicException {
        loadData();
    }

   public boolean deactivate() {
        // se me debe permitir cancelar el deactivate
        return true;
    }
     private void loadData() throws BasicException {
         Boolean flag=m_App.getAppUserView().getUser().hasPermission("BreakRejection");
       Approve.setVisible(flag );
       jTextField1.setVisible(flag);
       jLabel1.setVisible(flag);

           btable = BreakageDetailTable.loadInstance(m_App);
            jTable1.setModel(btable.getdiscountTableModel());

        TableColumnModel jColumns = jTable1.getColumnModel();
        
        jColumns.getColumn(0).setPreferredWidth(100);
        jColumns.getColumn(0).setResizable(false);
        jColumns.getColumn(1).setPreferredWidth(200);
        jColumns.getColumn(1).setResizable(false);
        jColumns.getColumn(2).setPreferredWidth(80);
        jColumns.getColumn(2).setResizable(false);
         jColumns.getColumn(3).setPreferredWidth(80);
        jColumns.getColumn(3).setResizable(false);
     }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Approve = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Select", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Approve.setText("Approve");
        Approve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApproveActionPerformed(evt);
            }
        });

        jLabel1.setText("No");

        jButton1.setText("Reject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Approve))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Approve, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApproveActionPerformed
        // TODO add your handling code here:
        try{
           int row=jTable1.getSelectedRowCount();
           int rowarr[]=jTable1.getSelectedRows();

           String rno=jTextField1.getText();
           if(rno.length()>1){
           for(int i=0;i<row;i++)
           {
              String id=btable.getdiscountTableModel().getValueAt(rowarr[i], 4).toString();
              new StaticSentence(m_App.getSession()
                           , "UPDATE STOCKDIARY SET RECEIVEDBY =?,RNO= ? WHERE ID =? AND RECEIVEDBY IS NULL"
                           , new SerializerWriteBasic(new Datas[] {Datas.STRING,Datas.STRING, Datas.STRING}))
                         .exec(new Object[] {m_App.getAppUserView().getUser().getName(),rno,id});

           }
           loadData();
           jTextField1.setText(null);
           }
           else
               JOptionPane.showMessageDialog(this, "Please Enter The Number ", "Cannot Insert", JOptionPane.OK_OPTION);
        }
        catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_ApproveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try{
           int row=jTable1.getSelectedRowCount();
           int rowarr[]=jTable1.getSelectedRows();

         //  String rno=jTextField1.getText();
         //  if(rno.length()>1){
           for(int i=0;i<row;i++)
           {
             // String id=btable.getdiscountTableModel().getValueAt(rowarr[i], 4).toString();
              String item=btable.getdiscountTableModel().getValueAt(rowarr[i], 5).toString();
              Double qty=-1 * (Double)btable.getdiscountTableModel().getValueAt(rowarr[i], 2);
              String id=btable.getdiscountTableModel().getValueAt(rowarr[i], 4).toString();
              int cnt= new StaticSentence(m_App.getSession()
                           , "UPDATE STOCKDIARY SET RECEIVEDBY =? WHERE ID =? AND RECEIVEDBY IS NULL"
                           , new SerializerWriteBasic(new Datas[] {Datas.STRING, Datas.STRING}))
                         .exec(new Object[] {"Rejected",id});
              if(cnt>0)
              new StaticSentence(m_App.getSession()
                           , "UPDATE STOCKCURRENT SET UNITS =(UNITS + ? ) WHERE PRODUCT =?"
                           , new SerializerWriteBasic(new Datas[] {Datas.DOUBLE, Datas.STRING}))
                         .exec(new Object[] {qty,item});
              

           }
           loadData();
           jTextField1.setText(null);
       //    }
        //   else
       //        JOptionPane.showMessageDialog(this, "Please Enter The Number ", "Cannot Insert", JOptionPane.OK_OPTION);
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Approve;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
