/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FacilityBillingConfirmation.java
 *
 * Created on 13-Jul-2011, 16:16:56
 */

package com.openbravo.pos.clubmang;

import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.data.loader.SerializerWriteString;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.pos.clubmang.FacilityApprovalRitesModel.AllFacilityLine;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.JPanelView;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import javax.swing.AbstractListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author swathi
 */
public class FacilityBillingConfirmation extends javax.swing.JPanel implements JPanelView,BeanFactoryApp {

    private AppView m_App;
    private DataLogicFacilities dmang;
    private DataLogicSales m_dlSales;
    private FacilityApprovalRitesModel frmodel;
    private AllFacilityListModel afmodel;
    private AllCardConfirmFacilities cfmodel;
    private Boolean flag;

    /** Creates new form FacilityBillingConfirmation */
    public FacilityBillingConfirmation() {
        initComponents();
    }

    public String getTitle() {
        return "FacilityBillingConfirmation";
    }

    public void activate() throws BasicException {
        frmodel = new FacilityApprovalRitesModel();
        List<FacilityApprovalRitesModel.AllFacilityLine> flist=frmodel.loadinstanceofallfacility(m_App);
        afmodel=new AllFacilityListModel(flist);
        jList1.setModel(afmodel);
        List l= new ArrayList();
        cfmodel=new AllCardConfirmFacilities(l);
        jList2.setModel(cfmodel);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jLabel2.setVisible(false);
    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }

    public void init(AppView app) throws BeanFactoryException {
        m_App = app;
        dmang = (DataLogicFacilities) app.getBean("com.openbravo.pos.clubmang.DataLogicFacilitiesCreate");
        m_dlSales = (DataLogicSales) m_App.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");

    }

    public Object getBean() {
        return this;
    }

    public void load(int i) throws BasicException{
        //frmodel = new FacilityApprovalRitesModel();
        //List<FacilityApprovalRitesModel.AllFacilityLine> flist=frmodel.loadinstanceofallfacility(m_App);
       // afmodel=new AllFacilityListModel(flist);
        List<FacilityApprovalRitesModel.CardConfirmationFacilitiesline> clist=frmodel.loadinstanceofcardfacilities(m_App,i);
        cfmodel=new AllCardConfirmFacilities(clist);
        //jList1.setModel(afmodel);
        jList2.setModel(cfmodel);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true); 
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Facilities");
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(40, 60, 100, 20);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 90, 180, 110);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jList2.setName("jList2"); // NOI18N
        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2);
        jScrollPane2.setBounds(310, 90, 170, 110);

        jLabel2.setText("Init.Billing");
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(310, 60, 120, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/1rightarrow.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(230, 90, 60, 25);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/1leftarrow.png"))); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(230, 170, 60, 25);

        jButton3.setText("load Init.Billing");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(200, 20, 120, 23);

        jButton4.setText("Load Credit Confirm.");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(330, 20, 150, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            int row=jList1.getSelectedIndex();
            if(row>=0){
                FacilityApprovalRitesModel.AllFacilityLine aflist=(AllFacilityLine) afmodel.getElementAt(row);
                String id=aflist.getId();
                if(flag){                
                new StaticSentence(m_App.getSession(), "UPDATE FACILITY SET INITCONTROL=TRUE WHERE ID=?  ",SerializerWriteString.INSTANCE).exec(id);
                load(0);
                }
                else{                
                new StaticSentence(m_App.getSession(), "UPDATE FACILITY SET CONFIRMCONTROL=TRUE WHERE ID=?  ",SerializerWriteString.INSTANCE).exec(id);
                load(1);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Select any one facility to add ");

            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            int row=jList2.getSelectedIndex();
            if(row>=0){
                FacilityApprovalRitesModel.CardConfirmationFacilitiesline cflist=(FacilityApprovalRitesModel.CardConfirmationFacilitiesline) cfmodel.getElementAt(row);
                String id=cflist.getId();
                if(flag){                
                new StaticSentence(m_App.getSession(), "UPDATE FACILITY SET INITCONTROL=FALSE WHERE ID=?",new SerializerWriteBasic(new Datas[]{Datas.STRING})).exec(new Object[]{id});
                load(0);
                }else{                
                new StaticSentence(m_App.getSession(), "UPDATE FACILITY SET CONFIRMCONTROL=FALSE WHERE ID=?",new SerializerWriteBasic(new Datas[]{Datas.STRING})).exec(new Object[]{id});
                load(1);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Select any one facility to remove");
            }

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            jLabel2.setVisible(true);
            jLabel2.setText("Init.Billing");
            flag=true;
            load(0);
        } catch (BasicException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
              jLabel2.setVisible(true);
            jLabel2.setText("Credit Confirm");
            flag=false;
            load(1);
        } catch (BasicException ex) {
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables



    private class AllFacilityListModel extends AbstractListModel {
        private java.util.List<FacilityApprovalRitesModel.AllFacilityLine> flist;
        public AllFacilityListModel(java.util.List<FacilityApprovalRitesModel.AllFacilityLine> flist) {
            this.flist = flist;
        }
        public int getSize() {
            return flist.size();
        }
        public Object getElementAt(int i) {
            return flist.get(i);
        }
        public void remove(int i){
             flist.remove(i);
        }

    }

    private class AllCardConfirmFacilities extends AbstractListModel {
        private java.util.List<FacilityApprovalRitesModel.CardConfirmationFacilitiesline> clist;
        public AllCardConfirmFacilities(java.util.List<FacilityApprovalRitesModel.CardConfirmationFacilitiesline> clist) {

            this.clist = clist;
        }
        public int getSize() {
            return clist.size();
        }
        public Object getElementAt(int i) {
            return clist.get(i);
        }
        public void remove(int i){
             clist.remove(i);
        }

    }

}
