/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccEntryCongDetail.java
 *
 * Created on May 7, 2009, 5:39:08 PM
 */

package com.openbravo.pos.Accounts;

import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SerializerReadClass;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;
//import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author swathi
 */
public class AccEntryCongDetail extends javax.swing.JDialog {

    /** Creates new form AccEntryCongDetail */
     private List<AccEntryConfTableModel.EntryLine> entrylist;
      private final  String[] Header={"Account","Debit","Credit"};
     private boolean resultok = false;
    private AppView m_App;
  //  private MoneyCollectionTableModel mcModel;
    /** Creates new form CollectionTransferDetail */
    public AccEntryCongDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    protected AccEntryCongDetail(Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AccEntryCongDetail(Frame parent,AppView app) {
        this(parent, true);
        this.m_App=app;
    }

    public AccEntryCongDetail(Dialog parent,AppView app) {
        this(parent, true);
        this.m_App=app;
    }

    protected static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window)parent;
        } else {
            return getWindow(parent.getParent());
        }
    }


    public static AccEntryCongDetail getDialog(Component parent,AppView app) {

        Window window = getWindow(parent);

        AccEntryCongDetail ct;

        if (window instanceof Frame) {
            ct = new AccEntryCongDetail((Frame) window,app);
        } else {
            ct = new AccEntryCongDetail((Dialog) window,app);
        }

        return ct;
    }
    @SuppressWarnings("empty-statement")

   public AbstractTableModel getTableModel() {
        return new AbstractTableModel() {
            @Override
            public String getColumnName(int column) {
                return AppLocal.getIntString(Header[column]);
            }
            public int getRowCount() {
                return entrylist.size();
            }
            public int getColumnCount() {
                return Header.length;
            }


            public Object getValueAt(int row, int column) {
                AccEntryConfTableModel.EntryLine cd=entrylist.get(row);
                switch (column) {
                case 0: return cd.getcreatedby();///account name
                case 1: return Formats.CURRENCY.formatValue(cd.getDebit());
                case 2: return Formats.CURRENCY.formatValue(cd.getCredit());


                default: return null;
                }
            }
        };
    }
    public  boolean showDialog(String id) throws BasicException {
      entrylist=new ArrayList<AccEntryConfTableModel.EntryLine>();
      List<AccEntryConfTableModel.EntryLine> chdetail = new StaticSentence(m_App.getSession(),
                " SELECT  A1.TID,A1.DATE,A1.NARRATION,CASE WHEN A1.TRANSTYPE='D' THEN A1.AMOUNT ELSE NULL END" +
                " ,CASE WHEN A1.TRANSTYPE='C' THEN A1.AMOUNT ELSE NULL END,A.NAME,A.NAME FROM ACCOUNTJOURNALDUP A1,ACCOUNTMASTER A WHERE A1.TID=? AND A1.ACCOUNTID=A.ID "
                , new SerializerWriteBasic(new Datas[]{Datas.STRING})
                , new SerializerReadClass(AccEntryConfTableModel.EntryLine.class))
                .list(new Object[]{id});
      entrylist.addAll(chdetail);
      jTable1.setModel(getTableModel());
      TableColumnModel cmodel=jTable1.getColumnModel();
      
      if(chdetail.size()>0)
       jTextArea1.setText(chdetail.get(0).getTransref());
      setVisible(true);
      return resultok;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Transaction Detail");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel2.setText("Narration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
