/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompanyCreator.java
 *
 * Created on Jul 23, 2009, 11:58:28 AM
 */

package com.openbravo.pos.Accounts;

//import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;
import com.openbravo.data.gui.JMessageDialog;
import com.openbravo.data.gui.MessageInf;
import com.openbravo.data.loader.BatchSentence;
import com.openbravo.data.loader.BatchSentenceResource;
import com.openbravo.data.loader.Datas;
//import com.openbravo.data.loader.PreparedSentence;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.data.loader.Session;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.AppProperties;
//import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.AppViewConnection;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.io.File;
//import java.net.InetAddress;
import java.net.InetAddress;
import java.util.Date;
import java.util.UUID;
import java.util.regex.Matcher;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author swathi
 */
public class CompanyCreator extends javax.swing.JDialog {
    
    private Session session;
    private AppProperties m_props;
    public CompanyCreator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    protected CompanyCreator(Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public CompanyCreator(Frame parent,Session s) {
        this(parent, true);
        this.session=s;
    }

    public CompanyCreator(Dialog parent,Session s) {
        this(parent, true);
        this.session=s;
    }

    protected static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window)parent;
        } else {
            return getWindow(parent.getParent());
        }
    }


    public static CompanyCreator getDialog(Component parent,Session s) {
        Window window = getWindow(parent);
        CompanyCreator ct;
        if (window instanceof Frame) {
            ct = new CompanyCreator((Frame) window,s);
        } else {
            ct = new CompanyCreator((Dialog) window,s);
        }
        return ct;
    }
    public void ShowDialog(AppProperties props){
      m_props=props;
      companyname.setText(null);
      desc.setText(null);
      crdate.setText(null);
      path.setText(null);
      setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        companyname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        crdate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Create Company");
        setResizable(false);

        jLabel1.setText("Company Name");
        jLabel1.setName("jLabel1"); // NOI18N

        companyname.setName("companyname"); // NOI18N
        companyname.setNextFocusableComponent(desc);

        jLabel2.setText("Description ");
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        desc.setColumns(20);
        desc.setRows(5);
        desc.setName("desc"); // NOI18N
        desc.setNextFocusableComponent(jButton1);
        jScrollPane1.setViewportView(desc);

        jLabel3.setText("Start Date");
        jLabel3.setName("jLabel3"); // NOI18N

        crdate.setEditable(false);
        crdate.setName("crdate"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/date.png"))); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setNextFocusableComponent(jButton2);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Save");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Path");
        jLabel4.setName("jLabel4"); // NOI18N

        path.setName("path"); // NOI18N

        jButton3.setText("Browse");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(crdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(companyname, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(path, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(companyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(crdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date date;
        try{
            date=(Date)Formats.DATE.parseValue(crdate.getText());
        }catch(Exception e){
            date=new Date();
        }
        date=JCalendarDialog.showCalendar(this, date);
        if(date!=null){
           crdate.setText(Formats.DATE.formatValue(date));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
          String cname=companyname.getText();
          String cdate=crdate.getText();
          boolean flag=false;
          File f;
          if(path.getText().length()>0){
            f=new File(path.getText());
            if(f.isDirectory()==true)
              flag=true;
          }
          if(flag && cname.length()>0 && cdate.length()>0 ){
              String type="jdbc:hsqldb:hsql:";
              Boolean b=true;
             String url=type+"//"+InetAddress.getLocalHost().getHostAddress()+"/"+cname;
             Object[] values=new Object[]{UUID.randomUUID().toString(),cname.trim(),desc.getText().trim(),Formats.DATE.parseValue(cdate),path.getText(),url,"false",new Date(),b};
             //praveen:changed desc to descr

             new StaticSentence(session, "INSERT INTO COMPANY (ID,NAME,DESCR,CRDATE,DATABASEPATH,URL,ACTIVE,TODAYDATE,FLAG) VALUES (?,?,?,?,?,?,?,?,?)"
               , new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING,Datas.STRING,Datas.TIMESTAMP,Datas.STRING,Datas.STRING,Datas.STRING,Datas.TIMESTAMP,Datas.BOOLEAN})).exec(values);
             String pathtemp=path.getText()+"/"+cname;
             File ftemp=new File(pathtemp);
             if(!ftemp.isDirectory())
               new File(pathtemp).mkdir();
             
             //execute the script to create all the tables
             session.close();
             
             session = AppViewConnection.createSession(m_props,url,true);
             String sScript ="/com/openbravo/pos/scripts/hsqldb-create.sql";
             BatchSentence bsentence = new BatchSentenceResource(session, sScript);
             bsentence.putParameter("APP_ID", Matcher.quoteReplacement(AppLocal.APP_ID));
             bsentence.putParameter("APP_NAME", Matcher.quoteReplacement(cname));
             bsentence.putParameter("APP_VERSION", Matcher.quoteReplacement(AppLocal.APP_VERSION));
             java.util.List l = bsentence.list();
             if (l.size() > 0) {
                 JMessageDialog.showMessage(this, new MessageInf(MessageInf.SGN_WARNING, AppLocal.getIntString("Database.ScriptWarning"), l.toArray(new Throwable[l.size()])));
             }
             url=m_props.getProperty("db.URL");
             session = AppViewConnection.createSession(m_props,url,true);
             ShowDialog(m_props);
            
          }else{
            JOptionPane.showMessageDialog(this, "Incorrect values .Please check the values", "Cannot Save", JOptionPane.ERROR_MESSAGE);
            if(session!=null)
                session.close();
            JOptionPane.showMessageDialog(this, "Error while creating company", "Error", JOptionPane.ERROR_MESSAGE);
          }
         }catch(Exception e){
           e.printStackTrace();
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        try{
         if(path.getText().length()>0){
          File f=new File(path.getText());
          fc.setCurrentDirectory(f);
         }else{
           fc.setCurrentDirectory(null);
         }
        }catch(Exception e){
            fc.setCurrentDirectory(null);
        }

        fc.showOpenDialog(new Frame());
        File curDir = fc.getCurrentDirectory();
        path.setText(fc.getSelectedFile().getAbsolutePath());
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField companyname;
    private javax.swing.JTextField crdate;
    private javax.swing.JTextArea desc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField path;
    // End of variables declaration//GEN-END:variables

}
