/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WarehouseWiseBrkUpReport.java
 *
 * Created on 31-Jul-2013, 17:22:13
 */
package com.openbravo.pos.Accounts;

import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;
import com.openbravo.data.loader.Session;
import com.openbravo.format.Formats;
import com.openbravo.pos.clubmang.DataSourceProvider;
import com.openbravo.pos.clubmang.JasperReportNew;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.JPanelView;
import com.openbravo.pos.forms.LookupUtilityImpl;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import net.sf.jasperreports.engine.JasperPrint;

/**
 *
 * @author user
 */
public class WarehouseWiseBrkUpReport extends javax.swing.JPanel implements JPanelView, BeanFactoryApp{
    
    //  private Date sdate;
    //  private Date edate;
      private AppView m_app;
      private String reportType="WareHouseWiseReport";
      private List<WarehouseWiseReportModel.StockDetailsline> stockList;
      private WarehouseWiseReportModel dbmodel;
      private DataLogicSales dlsales;
   
    /** Creates new form WarehouseWiseBrkUpReport */
    public WarehouseWiseBrkUpReport() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel2.setText("As On :");
        jLabel2.setName("jLabel2"); // NOI18N

        jTextField2.setName("jTextField2"); // NOI18N

        jButton2.setText("Date");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Generate");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jButton3)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(180, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      Date date;
       /* try {
            date= (Date) Formats.DATE.parseValue(jTextField2.getText());
        } catch (BasicException e) {
            date = null;
        }
            
      date = JCalendarDialog.showCalendar(this, date);
        if (date != null) {
            Calendar cal=Calendar.getInstance();
            cal.setTimeInMillis(date.getTime());
            cal.set(Calendar.DATE, cal.getActualMaximum(Calendar.DATE));
            date.setTime(cal.getTimeInMillis());
            jTextField2.setText(Formats.DATE.formatValue(date));
        }*/
      
     
        try {
            date = (Date) Formats.DATE.parseValue(jTextField2.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendarTimeHours(this, date);
        if (date != null) {
            jTextField2.setText(Formats.DATE.formatValue(date));
        }
      
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       try {
           /* Date sdate = (Date) Formats.DATE.parseValue(jTextField1.getText());
               Date edate = (Date) Formats.DATE.parseValue(jTextField2.getText());
           CalculationLogicTwo clt = null;
                       clt = new CalculationLogicTwo(sdate, edate, m_app,dlsales);
                       clt.Calculate("");
                       List<CalculationLogicTwo.StockBean> v = clt.getList();
                       DataSourceProvider data1 = new DataSourceProvider(v);
                       DataSourceForCurrentStock dsfc = new DataSourceForCurrentStock(v);
                       data1.setDataSource(dsfc);
                       Map reportparams = new HashMap();*/
//           Date sdate = (Date) Formats.DATE.parseValue(jTextField1.getText());
                       Date edate = (Date) Formats.DATE.parseValue(jTextField2.getText());
                       CalculationLogicTwo clt = null;
                       clt = new CalculationLogicTwo(edate, m_app,dlsales);
                       clt.Calculate("");
                       List<CalculationLogicTwo.StockBean> v = clt.getList();
                       Collections.sort(v);
                       Map<String, String> wareHouse = clt.getWHN();
                      
                       DataSourceProvider data1 = new DataSourceProvider(v);
                       DataSourceForCurrentStock dsfc = new DataSourceForCurrentStock(v);
                       data1.setDataSource(dsfc);
                       Map reportparams = new HashMap();
                       int i = 1;
                       for (Map.Entry<String, String> entry : wareHouse.entrySet()) {
                            String string = entry.getKey();
                            String string1 = entry.getValue();
                            reportparams.put("W"+i, string1);
                            i++;
                        } 
                       
           
           
                reportparams.put("companyName", m_app.getSession().getCompanyName());
                reportparams.put("companyAddress", m_app.getSession().getCompanyAddress());
//      
                JasperPrint jp = JasperReportNew.runReport(m_app, "./reports/com/openbravo/reports/C1.jrxml", reportparams, false, data1, true, null);

           
           
           // TODO add your handling code here:
        } catch (BasicException ex) {
            //Logger.getLogger(IncomeAndExpenditureAccount.class.getName()).log(Level.SEVERE, null, ex);
            //clogic.Calculate("");
            ex.printStackTrace();
        }
        
        
}//GEN-LAST:event_jButton3ActionPerformed

 





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    public String getTitle() {
        return "Warehousewise Report";    
    }

    public void activate() throws BasicException {
        reset();
    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
     return this;
    }

    public void init(AppView app) throws BeanFactoryException {
        m_app=app;
        dlsales=(DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
        
    }

    public Object getBean() {
       return this;
    }

    private void reset() {
   
       // jTextField1.setText("");
       jTextField2.setText("");
   }
}
