/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditorDialog.java
 *
 * Created on May 14, 2009, 10:17:16 AM
 */

package com.openbravo.pos.Accounts;

import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.SerializerReadBasic;
import com.openbravo.data.loader.SerializerWriteString;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.pos.clubmang.DataLogicFacilities;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author swathi
 */
public class BREditor extends javax.swing.JDialog {

    /** Creates new form EditorDialog */
     private AppView mapp;
     private DataLogicFacilities dlfac;
    public BREditor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    protected BREditor(Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public BREditor(Frame parent,AppView app,DataLogicFacilities dlfac) {
        this(parent, true);
        this.mapp=app;
        this.dlfac=dlfac;
    }

    public BREditor(Dialog parent,AppView app,DataLogicFacilities dlfac) {
        this(parent, true);
        this.mapp=app;
        this.dlfac=dlfac;
    }

    protected static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window)parent;
        } else {
            return getWindow(parent.getParent());
        }
    }


    public static BREditor getDialog(Component parent,AppView app,DataLogicFacilities dlfac) {

        Window window = getWindow(parent);

        BREditor ct;

        if (window instanceof Frame) {
            ct = new BREditor((Frame) window,app,dlfac);
        } else {
            ct = new BREditor((Dialog) window,app,dlfac);
        }

        return ct;
    }
   public  void showDialog(String tid) throws BasicException{
       int status=0;
       List<Object[]> trans=new StaticSentence(mapp.getSession()
                           , "SELECT TRANSREF,NARRATION,TRANSTYPE,TRANSNO,ACCOUNTID,AMOUNT,DATE,BALANCEAMOUNT,PAYMENTREF FROM ACCOUNTJOURNAL WHERE TID=?"
                           , SerializerWriteString.INSTANCE
                           ,new SerializerReadBasic(new Datas[]{Datas.STRING,Datas.STRING,Datas.STRING,Datas.STRING,Datas.STRING,Datas.DOUBLE,Datas.TIMESTAMP,Datas.DOUBLE,Datas.STRING})).list(tid);
       if(trans.size()>0){
           List list=dlfac.getMembersAccountIDsALL();
           for(Object[] obj:trans){
               //Object[] obj1=new Object[]{obj[4]};
              if(list.contains(obj[4])){
                  status=1;//contains mem account;
                break;
              }

           }
           //status=1;
           BvoucherEntry12.init(mapp);
           BvoucherEntry12.setValues(trans,tid,this,status);
       }
       setVisible(true);
   }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BvoucherEntry12 = new com.openbravo.pos.Accounts.VoucherEntry1();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Voucher Editor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BvoucherEntry12, javax.swing.GroupLayout.PREFERRED_SIZE, 755, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BvoucherEntry12, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.openbravo.pos.Accounts.VoucherEntry1 BvoucherEntry12;
    // End of variables declaration//GEN-END:variables

}
