/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayPurchaseOrderList.java
 *
 * Created on 23-Nov-2011, 11:20:48
 */
package com.openbravo.pos.inventory;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.pos.clubmang.PurchaseJournalTable.purchase;
import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author swathi
 */
public class DisplayPurchaseOrderList extends javax.swing.JDialog {

    public int resultok;
    private AppView app;
    private List<purchase> plist;
    private ComboBoxValModel pono;

    public int getResultok() {
        return resultok;
    }

    public void setResultok(int resultok) {
        this.resultok = resultok;
    }

    /** Creates new form DisplayPurchaseOrderList */
    protected DisplayPurchaseOrderList(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DisplayPurchaseOrderList(Frame parent, AppView app) {
        super(parent, true);
        this.app = app;
        this.pono = new ComboBoxValModel();
        initComponents();
    }

    public DisplayPurchaseOrderList(Dialog parent, AppView app) {
        super(parent, true);
        this.app = app;
        this.pono = new ComboBoxValModel();
        initComponents();
    }

    protected DisplayPurchaseOrderList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    protected static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window) parent;
        } else {
            return getWindow(parent.getParent());
        }
    }

    public static DisplayPurchaseOrderList getDialog(Component parent, AppView app) {

        Window window = getWindow(parent);

        DisplayPurchaseOrderList dP;

        if (window instanceof Frame) {
            dP = new DisplayPurchaseOrderList((Frame) window, app);
        } else {
            dP = new DisplayPurchaseOrderList((Dialog) window, app);
        }

        return dP;
    }

    public int showDialog(List<purchase> list) throws BasicException {
        jButton1.setText("Ok");
        this.plist = list;
        pono = new ComboBoxValModel(plist);
        jComboBox1.setModel(pono);
        this.setVisible(true);
        return resultok;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(300, 140));
        getContentPane().setLayout(null);

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setText("PO No:");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton1)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 10, 210, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        try {
            String ponor = jComboBox1.getSelectedItem().toString();
            resultok = Integer.parseInt(ponor);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        if (jComboBox1.getSelectedItem().toString() != null) {
            String ponor = jComboBox1.getSelectedItem().toString();
            resultok = Integer.parseInt(ponor);
            setResultok(resultok);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "select purchsae order");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
