//<class name="SMS Password"/>


package com.openbravo.pos.sms;

import com.openbravo.basic.BasicException;
import com.openbravo.beans.JCalendarDialog;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.gui.MessageInf;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.PreparedSentence;
import com.openbravo.data.loader.SerializerReadBasic;
import com.openbravo.data.loader.SerializerReadString;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.data.loader.SerializerWriteString;
import com.openbravo.data.loader.StaticSentence;
import com.openbravo.data.loader.Transaction;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.format.Formats;
import com.openbravo.pos.clubmang.DataSourceProvider;
import com.openbravo.pos.clubmang.JasperReportNew;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.JPanelView;
import com.openbravo.pos.util.AltEncrypter;
import com.openbravo.pos.util.Hashcypher;
import java.lang.String;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.AbstractListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperPrint;
import com.openbravo.pos.clubmang.SmsTableModel;
import com.openbravo.pos.clubmang.SmsTableModel.smsgroup;
import java.awt.Color;
import java.awt.Component;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author user
 */
public class SmsSendernew extends javax.swing.JPanel implements JPanelView, BeanFactoryApp {
   
    private ComboBoxValModel groupname;
    private List<Object> lst; 
    List<Object> selectedMemList=new ArrayList<Object>();
    List<Object>memlist=null;
    private AppView m_app;
    private SmsConnection connection;
    private DirtyManager m_Dirty;
    private Object[] obj1;
    private String m_sPassword;
    private Date fromDate;
    private Date toDate;
    private SmsTableModel smstablemodel;
    private SmsTableInfo smsTable_info;
    private String mobilelist;
    /** Creates new form SmsSendernew */
    public SmsSendernew() {
        initComponents();
        
        activate_Btn.setVisible(false);
        groupName_combo.setSelectedIndex(-1);
        password_panel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        password_panel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        url = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        senderid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        urlref_combo = new javax.swing.JComboBox();
        API_KEY = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        seturldetails = new javax.swing.JButton();
        createGroup_label = new javax.swing.JPanel();
        crgrp_btn = new javax.swing.JButton();
        groupName_panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        groupname_text = new javax.swing.JTextField();
        save_grp_btn = new javax.swing.JButton();
        cancel_grp_btn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable(){public Component prepareRenderer(TableCellRenderer renderer,
            int rowIndex, int vColIndex) {
            Component c = super.prepareRenderer(renderer, rowIndex, vColIndex);
            if (c instanceof JComponent) {
                JComponent jc = (JComponent)c;
                jc.setToolTipText(String.valueOf(getValueAt(rowIndex, vColIndex)));

                if (rowIndex % 2 == 0 && !isCellSelected(rowIndex, vColIndex)) {
                    jc.setBackground(Color.lightGray);
                }
                else {
                    jc.setBackground(Color.white);
                }
                if(isCellSelected(rowIndex, vColIndex))
                jc.setBackground(Color.cyan);
            }
            return c;
        }};
        deactivate_btn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        deactivatedlist_check = new javax.swing.JCheckBox();
        activate_Btn = new javax.swing.JButton();
        group_list_panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        groupName_combo = new javax.swing.JComboBox();
        list_EditorPanel = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jButton15 = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane3.setViewportView(jTable1);

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setName("jPanel1"); // NOI18N

        jButton1.setText("Check Credit");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delivery Report");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setVisible(false);

        jTextField1.setName("jTextField1"); // NOI18N

        jLabel1.setText("Enter Mobile No:");
        jLabel1.setName("jLabel1"); // NOI18N

        jButton4.setText("Submit");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("please enter valid 10 digit No.");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel8.setText("From:");
        jLabel8.setName("jLabel8"); // NOI18N

        jTextField3.setName("jTextField3"); // NOI18N
        jTextField3.setEditable(false);

        jLabel9.setText("To:");
        jLabel9.setName("jLabel9"); // NOI18N

        jTextField4.setName("jTextField4"); // NOI18N
        jTextField4.setEditable(false);

        jButton8.setText("From");
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("To");
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel16.setText("OR");
        jLabel16.setName("jLabel16"); // NOI18N

        jTextField5.setName("jTextField5"); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jLabel17.setText("Member No : ");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText("Member Name : ");
        jLabel18.setName("jLabel18"); // NOI18N

        jTextField6.setName("jTextField6"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel1)
                                .addComponent(jLabel9))
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField4)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton9, 0, 1, Short.MAX_VALUE)
                                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(128, 128, 128))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9)))
                .addGap(28, 28, 28)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField6.setEnabled(false);

        password_panel.setName("password_panel"); // NOI18N

        jButton3.setText("Change Password");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout password_panelLayout = new javax.swing.GroupLayout(password_panel);
        password_panel.setLayout(password_panelLayout);
        password_panelLayout.setHorizontalGroup(
            password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, password_panelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        password_panelLayout.setVerticalGroup(
            password_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(password_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setVisible(false);

        url.setName("url"); // NOI18N

        jLabel4.setText("URL:");
        jLabel4.setName("jLabel4"); // NOI18N

        username.setName("username"); // NOI18N

        jLabel5.setText("Username:");
        jLabel5.setName("jLabel5"); // NOI18N

        jButton5.setText("Password");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Password:");
        jLabel6.setName("jLabel6"); // NOI18N

        jButton6.setText("Save");
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancel");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel3.setText("SenderId:");
        jLabel3.setName("jLabel3"); // NOI18N

        senderid.setName("senderid"); // NOI18N

        jLabel7.setText("URLRef:");
        jLabel7.setName("jLabel7"); // NOI18N

        urlref_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SEND_URL", "DELREP_URL", "CRCHK_URL", "PASSCH_URL" }));
        urlref_combo.setName("urlref_combo"); // NOI18N
        urlref_combo.setSelectedIndex(-1);

        API_KEY.setText("API_KEY:");
        API_KEY.setName("API_KEY"); // NOI18N

        jTextField2.setName("jTextField2"); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(API_KEY))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urlref_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(senderid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(257, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(senderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(urlref_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(API_KEY)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(19, 19, 19))
        );

        jPanel4.setName("jPanel4"); // NOI18N

        seturldetails.setText("Set URL Details ");
        seturldetails.setName("seturldetails"); // NOI18N
        seturldetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seturldetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seturldetails, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seturldetails)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(password_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(password_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Main SMS Menu ", jPanel1);

        createGroup_label.setName("createGroup_label"); // NOI18N

        crgrp_btn.setText("Create Group");
        crgrp_btn.setName("crgrp_btn"); // NOI18N
        crgrp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crgrp_btnActionPerformed(evt);
            }
        });

        groupName_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        groupName_panel.setName("groupName_panel"); // NOI18N

        jLabel10.setText("Group Name :- ");
        jLabel10.setName("jLabel10"); // NOI18N

        groupname_text.setName("groupname_text"); // NOI18N

        save_grp_btn.setText("Save");
        save_grp_btn.setName("save_grp_btn"); // NOI18N
        save_grp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_grp_btnActionPerformed(evt);
            }
        });

        cancel_grp_btn.setText("Cancel");
        cancel_grp_btn.setName("cancel_grp_btn"); // NOI18N
        cancel_grp_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_grp_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groupName_panelLayout = new javax.swing.GroupLayout(groupName_panel);
        groupName_panel.setLayout(groupName_panelLayout);
        groupName_panelLayout.setHorizontalGroup(
            groupName_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupName_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupname_text, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, groupName_panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(cancel_grp_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_grp_btn)
                .addGap(28, 28, 28))
        );
        groupName_panelLayout.setVerticalGroup(
            groupName_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupName_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupName_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(groupname_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(groupName_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_grp_btn)
                    .addComponent(cancel_grp_btn))
                .addContainerGap())
        );

        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "GroupName", "Id", "Date", "Active"
            }
        ));
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane4.setViewportView(jTable2);

        deactivate_btn.setForeground(new java.awt.Color(153, 0, 0));
        deactivate_btn.setText("Deactive");
        deactivate_btn.setName("deactivate_btn"); // NOI18N
        deactivate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deactivate_btnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setText("Group Details : ");
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("SMS Group Master");
        jLabel15.setName("jLabel15"); // NOI18N

        deactivatedlist_check.setText("Show Deactivated List");
        deactivatedlist_check.setName("deactivatedlist_check"); // NOI18N
        deactivatedlist_check.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deactivatedlist_checkItemStateChanged(evt);
            }
        });

        activate_Btn.setForeground(new java.awt.Color(0, 153, 0));
        activate_Btn.setText("Activate ");
        activate_Btn.setName("activate_Btn"); // NOI18N
        activate_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activate_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createGroup_labelLayout = new javax.swing.GroupLayout(createGroup_label);
        createGroup_label.setLayout(createGroup_labelLayout);
        createGroup_labelLayout.setHorizontalGroup(
            createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createGroup_labelLayout.createSequentialGroup()
                .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createGroup_labelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crgrp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(32, 32, 32)
                        .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(groupName_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createGroup_labelLayout.createSequentialGroup()
                                .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(deactivatedlist_check)
                                    .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createGroup_labelLayout.createSequentialGroup()
                                            .addComponent(activate_Btn)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(deactivate_btn))
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(179, 179, 179))))
                    .addGroup(createGroup_labelLayout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(jLabel15)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        createGroup_labelLayout.setVerticalGroup(
            createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createGroup_labelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(36, 36, 36)
                .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(groupName_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crgrp_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(deactivatedlist_check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createGroup_labelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(createGroup_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deactivate_btn)
                            .addComponent(activate_Btn)))
                    .addComponent(jLabel14))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create Group for SMS", createGroup_label);

        group_list_panel.setName("group_list_panel"); // NOI18N

        jLabel11.setText("Group Name:");
        jLabel11.setName("jLabel11"); // NOI18N

        groupName_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Item1","Item2"}));
        groupName_combo.setName("groupName_combo"); // NOI18N
        groupName_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                groupName_comboItemStateChanged(evt);
            }
        });
        groupName_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupName_comboActionPerformed(evt);
            }
        });

        list_EditorPanel.setName("list_EditorPanel"); // NOI18N

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 102, 51));
        jButton14.setText("Add Members");
        jButton14.setName("jButton14"); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setText("Group List");
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setText("Member List ");
        jLabel12.setName("jLabel12"); // NOI18N

        jScrollPane5.setName("jScrollPane5"); // NOI18N

        jList3.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList3.setName("jList3"); // NOI18N
        jScrollPane5.setViewportView(jList3);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList2.setName("jList2"); // NOI18N
        jScrollPane2.setViewportView(jList2);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(153, 0, 0));
        jButton15.setText("Remove");
        jButton15.setName("jButton15"); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(0, 51, 153));
        saveBtn.setText("Save");
        saveBtn.setName("saveBtn"); // NOI18N
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(153, 0, 0));
        resetBtn.setText("Reset");
        resetBtn.setName("resetBtn"); // NOI18N
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout list_EditorPanelLayout = new javax.swing.GroupLayout(list_EditorPanel);
        list_EditorPanel.setLayout(list_EditorPanelLayout);
        list_EditorPanelLayout.setHorizontalGroup(
            list_EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(list_EditorPanelLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(list_EditorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resetBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_EditorPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(list_EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_EditorPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_EditorPanelLayout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199))))
        );
        list_EditorPanelLayout.setVerticalGroup(
            list_EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_EditorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(list_EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(list_EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(list_EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(list_EditorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton15)
                        .addComponent(resetBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout group_list_panelLayout = new javax.swing.GroupLayout(group_list_panel);
        group_list_panel.setLayout(group_list_panelLayout);
        group_list_panelLayout.setHorizontalGroup(
            group_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group_list_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(group_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(list_EditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(group_list_panelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(groupName_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        group_list_panelLayout.setVerticalGroup(
            group_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(group_list_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(group_list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupName_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_EditorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );

        jTabbedPane1.addTab("List of Group ", group_list_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
    }// </editor-fold>//GEN-END:initComponents

private void seturldetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seturldetailsActionPerformed
    
    
    reset();
    jPanel2.setVisible(false);
    jPanel3.setVisible(true); 
   
}//GEN-LAST:event_seturldetailsActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
    
    reset();
    jPanel2.setVisible(false); 
     jPanel3.setVisible(false);
    String sPassword;
    
    try {
            List<Object[]> obj=(List<Object[]>)new PreparedSentence(m_app.getSession(), "SELECT S.ID,S.URL,S.USERNAME,S.PASSWORD,S.ACTIVE,S.SENDERID,S.URLREF FROM SMSURL_TABLE S WHERE S.ACTIVE=TRUE AND S.URLREF='PASSCH_URL'",SerializerWriteString.INSTANCE, new SerializerReadBasic(new Datas[]{Datas.STRING,Datas.STRING,Datas.STRING,Datas.STRING,Datas.BOOLEAN,Datas.STRING,Datas.STRING})).list();
           for (Object[] url1 : obj) {
            //urlBean=(UrlBean)url;
            obj1=url1;
           }
        
        } catch (BasicException ex) {
            Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        if(obj1!=null){ 
            
            
         sPassword=obj1[3].toString();
         String sNewPassword = Hashcypher.changePasswordforSMS(this,  sPassword);
         String passwd=new AltEncrypter("key").decrypt(sNewPassword);
         System.out.println(passwd);
         
         System.out.println(sNewPassword );
         String response= new SmsConnection(m_app).connectionPasswordChange( obj1,passwd);
          
          if(response.equalsIgnoreCase("Your Password is changed Successfully !!!"))
          {
             try {
                  new PreparedSentence(m_app.getSession(), "UPDATE smsurl_table SET PASSWORD=? WHERE PASSWORD=?", new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING})).exec(new Object[]{sNewPassword,sPassword});
                } catch (BasicException ex) {
              Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
                 }
           JOptionPane.showMessageDialog(this,response);
         }  
          else
          {
              JOptionPane.showMessageDialog(this,response);
          }
          
          
        }  
        else{
              JOptionPane.showMessageDialog(this,"Please contact administrator to change password..!!");
        }
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String mobileno=jTextField1.getText();
        try {
            fromDate=(Date) Formats.DATE.parseValue(jTextField3.getText());
            toDate=(Date) Formats.DATE.parseValue(jTextField4.getText());
        } catch (BasicException ex) {
            Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
        }
        Pattern pattern=Pattern.compile("^[789]\\d{9}$");
        Matcher matcher=pattern.matcher(mobileno);
        if(matcher.matches())
        {
        if(mobileno.length()<10 ||mobileno.length()>10){
            JOptionPane.showMessageDialog(this,"Please enter valid 10 digit mobile number");
            jTextField1.setText("");
           jTextField1.requestFocus(true);
        }
        else{
            connection=new SmsConnection(m_app);
        String response=  connection.connectionDelReport(mobileno,fromDate,toDate);
        if(response==null)
        {
           JOptionPane.showMessageDialog(this,"No Active Url... Please Set url first...!!");  
        }
        else
        {
        
        //JOptionPane.showMessageDialog(this,response);
        generateReport( connection.getDelperlist());
        jPanel2.setVisible(false);
        }
        jPanel2.setVisible(false);
        }
        }
        else
        {
           JOptionPane.showMessageDialog(this,"Please enter valid 10 digit mobile number");
            jTextField1.setText("");
           jTextField1.requestFocus(true); 
        }
         
    // TODO add your handling code here:
}//GEN-LAST:event_jButton4ActionPerformed

public void generateReport(List<SmsConnection.DelRepBean> list)
{
     //List<SmsConnection.DelRepBean> list = new ArrayList<SmsConnection.DelRepBean>();
    Map reportparams = new HashMap();
      //list= new SmsConnection(m_app).getDelperlist();
     DataSourceProvider data1 = new DataSourceProvider(list);
     DataSourceForSMSDelReport dsfc = new DataSourceForSMSDelReport(list);
     data1.setDataSource(dsfc);
     reportparams.put("fromdate",fromDate );
     reportparams.put("todate",toDate );
     reportparams.put("cname", m_app.getSession().getCompanyName());
     reportparams.put("caddress", m_app.getSession().getCompanyAddress());
     reportparams.put("reportType","SMS Delivery Report for");
    JasperPrint jp = JasperReportNew.runReport(m_app, "./reports/com/openbravo/reports/smsdeliveryreport.jrxml", reportparams, false, data1, true, null); 
    
    
}





private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     reset();  
    jPanel2.setVisible(true);
        jTextField1.setText(""); 
        jTextField3.setText(""); 
        jTextField4.setText(""); 
        jTextField5.setText(""); 
        jTextField6.setText(""); 
        
      jPanel3.setVisible(false);
      jTextField1.requestFocus(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     reset();
    jPanel2.setVisible(false);
     jPanel3.setVisible(false);
   String response=new SmsConnection(m_app).connectionCreditCheck();
    
    if(response!=null)
    {
        JOptionPane.showMessageDialog(this,response);
    }
    else{
        JOptionPane.showMessageDialog(this,"No Active Url... Please Set url first...!! Response is : "+response);
    }
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
  String URL=url.getText(); 
   String USER=username.getText();
    String urlref=urlref_combo.getSelectedItem().toString();
    String sender_id=senderid.getText();
    String API_KEY=jTextField2.getText();
   int x=JOptionPane.showConfirmDialog(jPanel3, "Do you want to save");
   if(x==JOptionPane.YES_OPTION)
   {
        try {
            new PreparedSentence(m_app.getSession(), "INSERT INTO smsurl_table(ID, URL, USERNAME, PASSWORD, ACTIVE,SENDERID,URLREF,API_KEY) VALUES (?,?,?,?,?,?,?,?) ", new SerializerWriteBasic(new Datas[]{Datas.STRING, Datas.STRING, Datas.STRING, Datas.STRING, Datas.INT, Datas.STRING, Datas.STRING,Datas.STRING})).exec(new Object[]{UUID.randomUUID().toString(),URL, USER, m_sPassword, 1,sender_id,urlref,API_KEY});
        } catch (BasicException ex) {
            Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel3.setVisible(false);
   }
   else
   {
       url.setText("");
       username.setText("");
       m_sPassword="";
       jPanel3.setVisible(false);
       
   }
   
}//GEN-LAST:event_jButton6ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  String sNewPassword = Hashcypher.changePasswordforSMS(this);
        if (sNewPassword != null) {
            m_sPassword = sNewPassword;    
        }
    // TODO add your handling code here:
}//GEN-LAST:event_jButton5ActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    url.setText(null);
   username.setText(null); 
     m_sPassword="";
      jPanel3.setVisible(false);
      senderid.setText(null);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton7ActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
 Date date;
        try {
            date = (Date) Formats.DATE.parseValue( jTextField3.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendarTimeHours(this, date);
        if (date != null) {
            jTextField3.setText(Formats.DATE.formatValue(date));
        }
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
Date date;
        try {
            date = (Date) Formats.DATE.parseValue(jTextField4.getText());
        } catch (BasicException e) {
            date = null;
        }
        date = JCalendarDialog.showCalendarTimeHours(this, date);
        if (date != null) {
            jTextField4.setText(Formats.DATE.formatValue(date));
        }
}//GEN-LAST:event_jButton9ActionPerformed

    private void crgrp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crgrp_btnActionPerformed
       groupName_panel.setVisible(true);
       groupname_text.requestFocusInWindow();
       groupname_text.setText("");
    }//GEN-LAST:event_crgrp_btnActionPerformed

    private void cancel_grp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_grp_btnActionPerformed
      groupName_panel.setVisible(false);
    }//GEN-LAST:event_cancel_grp_btnActionPerformed

    private void save_grp_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_grp_btnActionPerformed
           
       if(groupname_text.getText()!=null && groupname_text.getText().trim().length()>0){ 
           
        
        
                  groupName_panel.setVisible(false);
                  String s=groupname_text.getText();
                  Date date=new Date();
                   UUID.randomUUID().toString();
                  //List<Object> lst;     
                Object obj = null;
                     System.out.println(m_app.getAppUserView().getUser().getName());
                try {
                     
            
            
            
            
            int info=new PreparedSentence(m_app.getSession()
                    , "INSERT INTO SMS_GROUP_LIST(GROUPNAME,DATE,ID,ACTIVE,CreatedBy,Createdhost) VALUES(?,?,?,?,?,?)"
                    , new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.TIMESTAMP,Datas.STRING,Datas.INT,Datas.STRING, Datas.STRING})).exec(new Object[]{s,date, UUID.randomUUID().toString(),1,m_app.getAppUserView().getUser().getName(),m_app.getProperties().getHost()});
                     
                     JOptionPane.showMessageDialog(this, "Saved Successfully..!! ", "Success", JOptionPane.INFORMATION_MESSAGE);
                   
                      try {

                            smstablemodel = SmsTableModel.loadSmsGroupNameList(m_app);
                            jTable2.setModel(smstablemodel.getTableModel());
                        } catch (Exception e) {
                            e.printStackTrace();
                        }  
                     
                     
                     
                     
           } catch (BasicException ex) {
              Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
       }
       else{
             JOptionPane.showMessageDialog(this, "Enter Group Name First ... !! " ,"Error", JOptionPane.ERROR_MESSAGE);
       }
 
    }//GEN-LAST:event_save_grp_btnActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
       if(jTabbedPane1.getSelectedIndex()==1){
           
          groupName_panel.setVisible(false); 
          deactivatedlist_check.setSelected(false);
            
          
          
          try {
                smstablemodel = SmsTableModel.loadSmsGroupNameList(m_app);
            } catch (BasicException ex) {
                Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
            }
           jTable2.setModel(smstablemodel.getTableModel());
           activate_Btn.setVisible(false);
           deactivate_btn.setVisible(true);
           deactivatedlist_check.setSelected(false);
          
          
       }
       
       
       // edited to  load all added list of group ....................................................... #aakash
       
       
       
       if(jTabbedPane1.getSelectedIndex()==2){
           groupName_combo.setSelectedIndex(-1);
           
           
           
           
           
           lst1 = new ArrayList<Object>();
           
           try {
              

                          lst1 =  new StaticSentence(m_app.getSession(), "SELECT GROUPNAME , ACTIVE FROM sms_group_list WHERE ACTIVE=TRUE", 
                                 SerializerWriteString.INSTANCE,
                                 SerializerReadString.INSTANCE).list();

                



            } catch (Exception e) {
                e.printStackTrace();
            }  
             
           
           
          groupname = new ComboBoxValModel(lst1);
          groupName_combo.setModel(groupname);
          groupName_combo.setSelectedIndex(-1);
           
           
          
       }
       
       
       
       
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void deactivate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deactivate_btnActionPerformed
        
        if(jTable2.getSelectedRow()!=-1){
            
            if(jTable2.getSelectedRow()< smstablemodel.getSize()){
              
                
               int x = JOptionPane.showConfirmDialog(password_panel, "Do You Want to Deativate Group ???? ", "Confirm", JOptionPane.YES_NO_OPTION); 
                if(x == JOptionPane.YES_OPTION){
                    
                    
                            
                int row = jTable2.getSelectedRow();
                
                smsgroup Showdata = smstablemodel.getsmsgroupList().get(row);
                
                String GroupId =  Showdata.getId();
                
                
                 try {



                     int update=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set Active=0 where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.STRING})).exec(new Object[]{   GroupId   });

                     int update1=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set DeacBy=? where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING})).exec(new Object[]{  m_app.getAppUserView().getUser().getName(),  GroupId   });

                     
                     int update2=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set DeacHost=? where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING})).exec(new Object[]{ m_app.getProperties().getHost() ,  GroupId   });

                     int update3=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set DeacDate=? where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.TIMESTAMP,Datas.STRING})).exec(new Object[]{ new Date() ,  GroupId   });

                     
                     
                     
                     
                        JOptionPane.showMessageDialog(this, " deactivated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        
                        
                        
                            
                       try {

                            smstablemodel = SmsTableModel.loadSmsGroupNameList(m_app);
                            jTable2.setModel(smstablemodel.getTableModel());
                            deactivatedlist_check.setSelected(false);
                            
                        } catch (Exception e) {
                            e.printStackTrace();
                        }  
                        
                        
                        
                      // jTable2.getSelectedRows();

                    } 


                 catch (BasicException ex) {
                  Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            
                }
               
             
             
             
             
             
            
       }
            
            
        }
        
        
       
        
    }//GEN-LAST:event_deactivate_btnActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
  
       
        
        try {
            int row = jList2.getSelectedIndex();
            if (row >= 0) {
                  String lst=jList2.getSelectedValue().toString();
                  
                   selectedMemList.add(lst);
                   memlist.remove(lst);
                 
            } else {
                JOptionPane.showMessageDialog(this, "Select any one member to add from memberlist");

            }
            } catch (Exception e) {
            e.printStackTrace();
        }  
        
        
        
        //   memlist=new ArrayList<Object>();
       //    memlist.addAll(selectedMemList);
        
        
          jList2.setModel(new ItemsListModel(memlist));
          jList3.setModel(new ItemsListModel(selectedMemList));
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed

        
         try {
            int row = jList3.getSelectedIndex();
            if (row >= 0) {
               
             String lst=jList3.getSelectedValue().toString();
                 
                 
                  selectedMemList.remove(lst);
                  memlist.add(lst);
                  
                 
                  jList3.setModel(new ItemsListModel(selectedMemList));
                  jList2.setModel(new ItemsListModel(memlist));
                   
             } else {
                JOptionPane.showMessageDialog(this, "Select any one member to add from memberlist");

            }
         } catch (Exception e) {
            e.printStackTrace();
         }      
        

     
        
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void groupName_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupName_comboActionPerformed
      
                   
    }//GEN-LAST:event_groupName_comboActionPerformed

    private void groupName_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_groupName_comboItemStateChanged
     
       if(groupName_combo.getSelectedIndex()!=-1) 
       {
        
           
             list_EditorPanel.setVisible(true);
           
           
            
            
            // edited to load list of members already grouped ....... ............................................#aakash
            
            
            selectedMemList = new ArrayList<Object> ();
            memlist = new ArrayList<Object>();
            
            String GroupName = groupName_combo.getSelectedItem().toString();
             
            
           
           
             try {
             //list = new StaticSentence(m_app.getSession(),  "SELECT A.NAME ,C.MOBILE FROM ACCOUNTMASTER A JOIN CUSTOMERS C ON a.id=c.account where c.mobile!='' and (LENGTH(C.MOBILE)=10 OR LENGTH(C.MOBILE)=13) ORDER BY NAME",
               
              memlist = new StaticSentence(m_app.getSession(),  "  SELECT concat(c.searchkey ,' - '  , c.name ) FROM CUSTOMERS C WHERE C.VISIBLE=TRUE AND C.ID NOT IN (SELECT L.MEMBERNAME FROM sms_grp_mem L , sms_group_list G WHERE L.ACTIVE=1 AND L.GROUPNAME = G.ID  AND G.GROUPNAME= ?  ) ORDER BY C.SEARCHKEY ",
                                                                   SerializerWriteString.INSTANCE,
                                                                   SerializerReadString.INSTANCE).list(GroupName);
            
         
             } catch (BasicException ex) {
            Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
            }
        
         jList2.setModel(new ItemsListModel(memlist)); 
            
            
            
         
         
         
         List<Object> list2=null;
           
             try {
             //list = new StaticSentence(m_app.getSession(),  "SELECT A.NAME ,C.MOBILE FROM ACCOUNTMASTER A JOIN CUSTOMERS C ON a.id=c.account where c.mobile!='' and (LENGTH(C.MOBILE)=10 OR LENGTH(C.MOBILE)=13) ORDER BY NAME",
               
              selectedMemList = new StaticSentence(m_app.getSession(),  " SELECT concat(c.searchkey ,' - '  , c.name ) FROM CUSTOMERS C WHERE C.ID IN (SELECT L.MEMBERNAME FROM sms_grp_mem L  , sms_group_list G WHERE L.ACTIVE=1 AND L.GROUPNAME = G.ID AND G.GROUPNAME = ?) ORDER BY C.SEARCHKEY ",
                                                                   SerializerWriteString.INSTANCE,
                                                                   SerializerReadString.INSTANCE).list(GroupName);
            
         
              
             
              
             } catch (BasicException ex) {
            Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
            }
        
         jList3.setModel(new ItemsListModel(selectedMemList)); 
         
         
         
         
         
            
        
       }
       else{
        list_EditorPanel.setVisible(false);
    }
       
        
    }//GEN-LAST:event_groupName_comboItemStateChanged

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
      
       if(groupName_combo.getSelectedIndex()!=-1){  
        
            
             
             
             
            try{
               Transaction t=new Transaction(m_app.getSession()) {
                    String GroupName = groupName_combo.getSelectedItem().toString();
                    String Group_ID = null;
                           @Override
                           
                           
               protected Object transact() throws BasicException {

                              Object o = null; 
                              o =  new StaticSentence(m_app.getSession(), "SELECT ID  FROM sms_group_list WHERE GROUPNAME =  ?", 
                                             SerializerWriteString.INSTANCE,
                                             SerializerReadString.INSTANCE).find(GroupName);

                               if(o!=null){
                                   Group_ID = o.toString();
                                }  



                       
                        if( Group_ID!=null){

                           new PreparedSentence(m_app.getSession(), "DELETE  FROM sms_grp_mem  WHERE GROUPNAME=? ", new SerializerWriteBasic(new Datas[]{Datas.STRING})).exec(new Object[]{Group_ID});
                           
                           
                            for(int i=0;i<selectedMemList.size();i++){

                                String SelectedMemName = selectedMemList.get(i).toString();
                                Object CustId = null; 
                                CustId =  new StaticSentence(m_app.getSession(), "SELECT ID  FROM customers  WHERE concat(searchkey ,' - '  , name ) =  ?", 
                                             SerializerWriteString.INSTANCE,
                                             SerializerReadString.INSTANCE).find(SelectedMemName);

                                
                                 new PreparedSentence(m_app.getSession()
                                  , "INSERT INTO sms_grp_mem ( ID , Groupname , Active, MemberName , CreatedBy , CreatedHost ,  CRDATE ) VALUES (?,?,?,?,?,?,?)"
                                  , new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING,Datas.INT,Datas.STRING,Datas.STRING,Datas.STRING,Datas.TIMESTAMP})
                                  ).exec(new Object[]{UUID.randomUUID().toString() , Group_ID , 1 , CustId , m_app.getAppUserView().getUser().getName(),m_app.getProperties().getHost() , new Date() });
                             
                             
                            }
                           
                           

                          }
           
            
            
            
                        
             
              return null;
              }
            };
            t.execute();
            
            JOptionPane.showMessageDialog(this, "Saved Successfully..!! ", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            
            
        }
        catch(Exception e){
            new MessageInf(e).show(getParent());
            e.printStackTrace();
            
            
        }
             
             
        
             
       }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
       groupName_combo.setSelectedIndex(-1);
       list_EditorPanel.setVisible(false);
       
    }//GEN-LAST:event_resetBtnActionPerformed

    private void deactivatedlist_checkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deactivatedlist_checkItemStateChanged
        if(deactivatedlist_check.isSelected()){
            
            try {

                    smstablemodel = SmsTableModel.loadSmsGroupNameList_Deactivated(m_app);
                    jTable2.setModel(smstablemodel.getTableModel());
                    activate_Btn.setVisible(true);
                    deactivate_btn.setVisible(false);
                } catch (Exception e) {
                    e.printStackTrace();
            }  
            
        }
        else{
            
                try {

                    smstablemodel = SmsTableModel.loadSmsGroupNameList(m_app);
                    jTable2.setModel(smstablemodel.getTableModel());
                    activate_Btn.setVisible(false);
                    deactivate_btn.setVisible(true);
                    
                } catch (Exception e) {
                    e.printStackTrace();
                }  
            
            
        }
    }//GEN-LAST:event_deactivatedlist_checkItemStateChanged

    private void activate_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activate_BtnActionPerformed
          if(jTable2.getSelectedRow()!=-1){
            
            if(jTable2.getSelectedRow()< smstablemodel.getSize()){
              
                
               int x = JOptionPane.showConfirmDialog(password_panel, "Do You Want to Activate Group ???? ", "Confirm", JOptionPane.YES_NO_OPTION); 
                if(x == JOptionPane.YES_OPTION){
                    
                    
                            
                int row = jTable2.getSelectedRow();
                
                smsgroup Showdata = smstablemodel.getsmsgroupList().get(row);
                
                String GroupId =  Showdata.getId();
                
                
                 try {



                     int update=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set Active=1 where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.STRING})).exec(new Object[]{   GroupId   });

                     int update1=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set CreatedBy=? where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING})).exec(new Object[]{  m_app.getAppUserView().getUser().getName(),  GroupId   });

                     
                     int update2=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set CreatedHost=? where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING})).exec(new Object[]{ m_app.getProperties().getHost() ,  GroupId   });

                     int update3=new PreparedSentence(m_app.getSession()
                        , "UPDATE sms_group_list set Date=? where ID=?"
                        , new SerializerWriteBasic(new Datas[]{Datas.TIMESTAMP,Datas.STRING})).exec(new Object[]{ new Date() ,  GroupId   });

                     
                     
                     
                     
                        JOptionPane.showMessageDialog(this, " Activated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                        
                        
                        
                            
                       try {

                            smstablemodel = SmsTableModel.loadSmsGroupNameList(m_app);
                            jTable2.setModel(smstablemodel.getTableModel());
                            deactivatedlist_check.setSelected(false);
                            
                        } catch (Exception e) {
                            e.printStackTrace();
                        }  
                        
                        
                        
                      // jTable2.getSelectedRows();

                    } 


                 catch (BasicException ex) {
                  Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            
                }
               
             
             
             
             
             
            
       }
            
            
        }
    }//GEN-LAST:event_activate_BtnActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        // String cust=null;
        String custoid;

        if (evt.getKeyText(evt.getKeyCode()).equals("Enter")) {
            String cust = jTextField5.getText();
            try {
                Object[] obj = (Object[]) new StaticSentence(m_app.getSession(), "SELECT ID,NAME,MOBILE FROM CUSTOMERS WHERE SEARCHKEY = ? ", SerializerWriteString.INSTANCE, new SerializerReadBasic(new Datas[]{Datas.STRING, Datas.STRING,Datas.STRING })).find(cust.toUpperCase());                      // #CHANGE BY AAKASH... ON 6TH DEC 2013
                if (obj == null) {
                    JOptionPane.showMessageDialog(this, " Member Not Found", "Error", JOptionPane.WARNING_MESSAGE);
                } else {
                    custoid = obj[0].toString();
                    String CustName  = obj[1].toString();
                   
                    jTextField6.setText(obj[1].toString());
                    if(obj[2]!=null){
                        String x = obj[2].toString();
                        if(x.length()>0){
                            jTextField1.setText(x);
                        }
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        else{
            jTextField6.setText(null);
        }
    }//GEN-LAST:event_jTextField5KeyPressed

   
     
       
      List<Object> lst1=new ArrayList<Object>();     
      public void grouplst(){
         try {
                      lst1 =  new StaticSentence(m_app.getSession(), "SELECT GROUPNAME,ACTIVE FROM sms_group_list WHERE ACTIVE=TRUE", 
                             SerializerWriteString.INSTANCE,
                             SerializerReadString.INSTANCE).list();
                      
                    } catch (BasicException ex) {
                        Logger.getLogger(SmsSendernew.class.getName()).log(Level.SEVERE, null, ex);
                    }
                        // jList1.setModel(new ItemsListModel(lst1));
          
        
           
            
        
          }
    
    
    
    
    
         private class ItemsListModel extends AbstractListModel {

        private java.util.List items;

        public ItemsListModel(java.util.List items) {
            this.items = items;
        }

        
        public int getSize() {
            return items.size();
        }

        public Object getElementAt(int i) {
            return items.get(i);
        }
    }
    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel API_KEY;
    private javax.swing.JButton activate_Btn;
    private javax.swing.JButton cancel_grp_btn;
    private javax.swing.JPanel createGroup_label;
    private javax.swing.JButton crgrp_btn;
    private javax.swing.JButton deactivate_btn;
    private javax.swing.JCheckBox deactivatedlist_check;
    private javax.swing.JComboBox groupName_combo;
    private javax.swing.JPanel groupName_panel;
    private javax.swing.JPanel group_list_panel;
    private javax.swing.JTextField groupname_text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel list_EditorPanel;
    private javax.swing.JPanel password_panel;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton save_grp_btn;
    private javax.swing.JTextField senderid;
    private javax.swing.JButton seturldetails;
    private javax.swing.JTextField url;
    private javax.swing.JComboBox urlref_combo;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

    public String getTitle() {
        
        return "SMSMaster";
        // throw new UnsupportedOperationException("Not supported yet.");
    }

    public void activate() throws BasicException {
        password_panel.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        Boolean flag = m_app.getAppUserView().getUser().hasPermission("SMS Password");
        if(flag)
        {
           password_panel.setVisible(true); 
        }
         
        Boolean flag1 = m_app.getAppUserView().getUser().hasPermission("Edit_Url_permission");
        if(flag1)
        {
           jPanel4.setVisible(true); 
        }
        else{
             jPanel4.setVisible(false); 
        }
         grouplst();
        reset();
       
        
        
       try {
            
            smstablemodel = SmsTableModel.loadSmsGroupNameList(m_app);
            jTable2.setModel(smstablemodel.getTableModel());
        } catch (Exception e) {
            e.printStackTrace();
        }  
        
       
            
     
       
       
          groupname = new ComboBoxValModel(lst1);
          groupName_combo.setModel(groupname);
          groupName_combo.setSelectedIndex(-1);
              //load();   
       
       
        
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public boolean deactivate() {
       
        return true;
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public JComponent getComponent() {
        return this;
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public void init(AppView app) throws BeanFactoryException {
       this.m_app=app;
         jTextField1.setText("");
         connection= (SmsConnection) app.getBean("com.openbravo.pos.sms.SmsConnection");
       
         
        //throw new UnsupportedOperationException("Not supported yet.");
    }

    public Object getBean() {
        return this;
        
        //throw new UnsupportedOperationException("Not supported yet.");
    }
    
    private void reset() {
        jTextField1.setText("");
        url.setText("");
        username.setText("");
        senderid.setText("");
        urlref_combo.setSelectedIndex(-1);
        jTextField2.setText("");
    }
}
