package com.openbravo.pos.clubmang;


import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.sales.QTicketLineInfo;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import javax.swing.JFrame;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * discountdetail.java
 *
 * Created on Jan 9, 2009, 1:18:31 PM
 */

/**
 *
 * @author swathi
 */
public class Details extends javax.swing.JDialog {

    /** Creates new form discountdetail */
    QTicketLineInfo qtline;
    DataLogicSales dlsales;
    public boolean resultok=false;
    private AppView app;    
    private int limit;
    private StringBuffer obj;
 



    protected Details(java.awt.Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public  Details(Frame parent,AppView app)
    {
        super(parent,true);
         this.app=app;         
         initComponents();
    }
     public  Details(Dialog parent,AppView app)
    {
        super(parent,true);
        this.app=app;       
        initComponents();
    }
    protected Details(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
      protected static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window)parent;
        } else {
            return getWindow(parent.getParent());
        }
    }


    public static Details getDialog(Component parent,AppView app) {

        Window window = getWindow(parent);

       Details dP;

        if (window instanceof Frame) {
            dP = new Details((Frame) window,app);
        } else {
            dP = new Details((Dialog) window,app);
        }

        return dP;
    }

    public  boolean showDialog(StringBuffer val) throws BasicException {
           this.obj = val;         
          jTextArea1.setText(val.toString());
           jTextArea1.setEditable(false);
          this.setVisible(true);
          return resultok;
          
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel7.setText("Details");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(115, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
