/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MappingRolesToFacility.java
 *
 * Created on 13-Jul-2011, 18:57:08
 */

package com.openbravo.pos.clubmang;

import com.openbravo.basic.BasicException;
import com.openbravo.data.gui.ComboBoxValModel;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.PreparedSentence;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.clubmang.FacilityApprovalRitesModel.AllUsersLine;
import com.openbravo.pos.clubmang.FacilityApprovalRitesModel.CardConfirmationFacilitiesline;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.forms.JPanelView;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author swathi
 */
public class MappingRolesToFacility extends javax.swing.JPanel implements JPanelView,BeanFactoryApp{

    private AppView m_App;
    private DataLogicFacilities dmang;
    private DataLogicSales m_dlSales;
    private FacilityApprovalRitesModel frmodel;
    private AllUsersListModel aumodel;    
    private ComboBoxValModel facmodel;

    /** Creates new form MappingRolesToFacility */
    public MappingRolesToFacility() {
        initComponents();
    }

    public String getTitle() {
        return "MappingRolesToFacility";
    }

    public void activate() throws BasicException {
        //jButton2.setEnabled(false);
        //jButton3.setEnabled(false);
    }

    public boolean deactivate() {
        return true;
    }

    public JComponent getComponent() {
        return this;
    }

    public void init(AppView app) throws BeanFactoryException {
        try {
            m_App = app;
            dmang = (DataLogicFacilities) app.getBean("com.openbravo.pos.clubmang.DataLogicFacilitiesCreate");
            m_dlSales = (DataLogicSales) m_App.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");
            frmodel = new FacilityApprovalRitesModel();
            load();
        } catch (BasicException ex) {
            ex.printStackTrace();
        }
    }

    public Object getBean() {
        return this;
    }

    public void load() throws BasicException{
        frmodel = new FacilityApprovalRitesModel();
        List list1 = frmodel.loadinstanceofcardfacilities(m_App,0);
        facmodel = new ComboBoxValModel(list1);
        jComboBox1.setModel(facmodel);
        List<FacilityApprovalRitesModel.AllUsersLine> flist=frmodel.loadinstanceofallusers(m_App);
        aumodel=new AllUsersListModel(flist);
        jList1.setModel(aumodel);      
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Facilities");
        jLabel1.setName("jLabel1"); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(30, 40, 60, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        add(jComboBox1);
        jComboBox1.setBounds(90, 40, 120, 20);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jList1.setName("jList1"); // NOI18N
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 120, 120, 130);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jList2.setName("jList2"); // NOI18N
        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2);
        jScrollPane2.setBounds(270, 120, 120, 130);

        jLabel2.setText("All Users");
        jLabel2.setName("jLabel2"); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(90, 90, 80, 20);

        jLabel3.setText("Mapped Users");
        jLabel3.setName("jLabel3"); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(270, 90, 110, 20);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/btnplus.png"))); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(220, 120, 30, 30);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/openbravo/images/btnminus.png"))); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(400, 120, 30, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            int row=jList1.getSelectedIndex();
            if(row>=0){
            FacilityApprovalRitesModel.CardConfirmationFacilitiesline cfline = (CardConfirmationFacilitiesline) jComboBox1.getSelectedItem();
            if(cfline==null){
            FacilityApprovalRitesModel.AllUsersLine aulist= (AllUsersLine) aumodel.getElementAt(row);
            String uid = aulist.getId();
            String id = cfline.getId();
            new PreparedSentence(m_App.getSession(), "UPDATE FACILITYCARDCONFIRM SET ROLE=ROLE"+"#"+"? WHERE ID=?", new SerializerWriteBasic(new Datas[]{Datas.STRING,Datas.STRING})).exec(new Object[]{uid,id});
         }else{
                JOptionPane.showMessageDialog(this, "Select Facility to map");

            }
            }else{
                JOptionPane.showMessageDialog(this, "Select user to map ");

            }
        }catch(Exception e){
            e.printStackTrace();
        }
        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:


        
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

private class AllUsersListModel extends AbstractListModel {
        private java.util.List<FacilityApprovalRitesModel.AllUsersLine> ulist;
        public AllUsersListModel(java.util.List<FacilityApprovalRitesModel.AllUsersLine> ulist) {
            this.ulist = ulist;
        }
        public int getSize() {
            return ulist.size();
        }
        public Object getElementAt(int i) {
            return ulist.get(i);
        }
        public void remove(int i){
             ulist.remove(i);
        }

    }

    /*private class AllCardConfirmFacilities extends AbstractListModel {
    private java.util.List<FacilityApprovalRitesModel.CardConfirmationFacilitiesline> clist;
    public AllCardConfirmFacilities(java.util.List<FacilityApprovalRitesModel.CardConfirmationFacilitiesline> clist) {

    this.clist = clist;
    }
    public int getSize() {
    return clist.size();
    }
    public Object getElementAt(int i) {
    return clist.get(i);
    }
    public void remove(int i){
    clist.remove(i);
    }

    }*/

}
