/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VoucherEntry.java
 *
 * Created on Mar 29, 2009, 4:29:50 PM
 */

package com.openbravo.pos.clubmang;

import com.openbravo.basic.BasicException;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.BeanFactoryApp;
import com.openbravo.pos.forms.BeanFactoryException;
import com.openbravo.pos.forms.JPanelView;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.JComponent;

/**
 *
 * @author swathi
 */
public class VoucherEntry extends javax.swing.JPanel implements JPanelView,BeanFactoryApp {

    /** Creates new form VoucherEntry */
    private DataLogicFacilities dlfac;
    public VoucherEntry() {
        initComponents();
        jList1.setVisible(false);
    }
     public String getTitle() {
       return null;
    }

    public void activate() throws BasicException {
      jList1.setVisible(false);
    }

    public boolean deactivate() {
      return true;
    }

    public JComponent getComponent() {
       return this;
    }

    public void init(AppView app) throws BeanFactoryException {
         dlfac=(DataLogicFacilities) app.getBean("com.openbravo.pos.clubmang.DataLogicFacilitiesCreate");
    }

    public Object getBean() {
       return this;
    }
     private class ItemsListModel extends AbstractListModel {
        private java.util.List items;
        public ItemsListModel(java.util.List items) {
            this.items = items;
        }
        public int getSize() {
            return items.size();
        }
        public Object getElementAt(int i) {
            return items.get(i);
        }


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        particulars = new javax.swing.JTextField();
        credit = new javax.swing.JTextField();
        debit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setAutoscrolls(true);
        setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setText("Receipts");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 30, 73, 23);

        jButton2.setText("Payments");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(0, 60, 79, 23);

        jButton3.setText("Journal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 90, 67, 23);

        jButton4.setText("Contra");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(0, 120, 65, 23);

        jButton5.setText("Purchases");
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 150, 81, 23);

        jButton6.setText("Sales");
        jPanel1.add(jButton6);
        jButton6.setBounds(0, 180, 57, 23);

        add(jPanel1);
        jPanel1.setBounds(569, 10, 90, 490);

        jPanel2.setBackground(java.awt.Color.green);
        jPanel2.setLayout(null);

        jLabel1.setText("Particulars");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(130, 10, 50, 14);

        jLabel2.setText("Credit");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(490, 10, 29, 14);

        jLabel3.setText("Debit");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(370, 10, 25, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "To", "By" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(0, 30, 37, 20);

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(300, 50, 260, 530);

        particulars.setBorder(null);
        particulars.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                particularsKeyReleased(evt);
            }
        });
        jPanel2.add(particulars);
        particulars.setBounds(100, 30, 219, 14);

        credit.setBorder(null);
        jPanel2.add(credit);
        credit.setBounds(480, 30, 76, 14);

        debit.setBorder(null);
        jPanel2.add(debit);
        debit.setBounds(360, 30, 74, 14);

        add(jPanel2);
        jPanel2.setBounds(0, 40, 0, 580);

        jLabel4.setText("jLabel4");
        add(jLabel4);
        jLabel4.setBounds(170, 50, 34, 14);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        debit.setVisible(false);
        credit.setVisible(true);
        jList1.setVisible(false);
        jPanel2.setBackground(Color.green);
        jLabel4.setText(jButton1.getText());
        repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         debit.setVisible(true);
        credit.setVisible(false);
        jList1.setVisible(false);
        jPanel2.setBackground(Color.yellow);
        jLabel4.setText(jButton2.getText());
        repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         debit.setVisible(true);
         credit.setVisible(false);
         jList1.setVisible(false);
         jPanel2.setBackground(Color.blue);
         jLabel4.setText(jButton3.getText());
        repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         debit.setVisible(false);
        credit.setVisible(true);
        jList1.setVisible(false);
        jPanel2.setBackground(Color.white);
        jLabel4.setText(jButton4.getText());
        repaint();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void particularsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_particularsKeyReleased
        // TODO add your handling code here:
        String name=particulars.getText();
        try {
            List acclist = dlfac.getsubAccounts(name.toUpperCase());
            jList1.setVisible(true);
            jList1.removeAll();
            jList1.setModel(new ItemsListModel(acclist));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_particularsKeyReleased

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        particulars.setText(jList1.getSelectedValue().toString());
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyText(evt.getKeyCode()).equals("Enter")){
           particulars.setText(jList1.getSelectedValue().toString());
        }
    }//GEN-LAST:event_jList1KeyPressed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equals("To")){
           debit.setVisible(false);
           credit.setVisible(true);
           jList1.setVisible(false);
        }
        else
            if(jComboBox1.getSelectedItem().toString().equals("By")){
                credit.setVisible(false);
                debit.setVisible(true);
                jList1.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged
/**//**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField credit;
    private javax.swing.JTextField debit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField particulars;
    // End of variables declaration//GEN-END:variables



}
