/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportType.java
 *
 * Created on Feb 22, 2009, 1:34:46 PM
 */

package com.openbravo.pos.ticket;

import com.openbravo.basic.BasicException;
import com.openbravo.data.loader.Datas;
import com.openbravo.data.loader.QBFCompareEnum;
import com.openbravo.data.loader.SerializerWrite;
import com.openbravo.data.loader.SerializerWriteBasic;
import com.openbravo.pos.forms.AppView;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.pos.reports.PanelReportBean;
import com.openbravo.pos.reports.ReportEditorCreator;
import java.awt.Component;

/**
 *
 * @author swathi
 */
public class ReportType extends javax.swing.JPanel implements ReportEditorCreator{

    /** Creates new form ReportType */
    private PanelReportBean   report;
    private AppView m_App;
    public ReportType(PanelReportBean   report1) {
     report =report1;
        initComponents();
    }
  public void init(AppView app) {
        m_App=app;
        DataLogicSales dlSales = (DataLogicSales) app.getBean("com.openbravo.pos.forms.DataLogicSalesCreate");

        // El modelo de categorias
           jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     ","YES" }));
 }
   public void activate() throws BasicException {
         jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     ","YES" }));
         jComboBox1.setSelectedIndex(0);
   }
   public SerializerWrite getSerializerWrite() {
        return new SerializerWriteBasic(
                new Datas[] {Datas.OBJECT, Datas.STRING});
    }
    public Component getComponent() {
        return this;
    }

    public Object createValue() throws BasicException {
         return new Object[] {
        QBFCompareEnum.COMP_NONE, "YES"
         };
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Report type"));

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Detail");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox1.getSelectedItem().toString().equals("YES"))
        {//IN (CUSTOMERS.ID,CUSTOMERS.ID+'#Guest 1',CUSTOMERS.ID+'#Guest 2',CUSTOMERS.ID+'#Guest 3',CUSTOMERS.ID+'#Guest 4',CUSTOMERS.ID+'#Guest 5' )
            report.setreporttoempty();
             report.setReport("/com/openbravo/reports/waiterbillwise1");
             report.setResourceBundle("com/openbravo/reports/costing_messages");
             report.setSentence("SELECT NAME,AMOUNT,SEARCHKEY,WNAME,ID,WID,LNAME FROM ( SELECT  CUSTOMERS.NAME AS NAME, BILL.AMOUNT AS AMOUNT,CUSTOMERS.SEARCHKEY AS SEARCHKEY,WAITER.NAME AS WNAME,BILL.ID AS ID,WAITER.ID AS WID,LOCATIONS.NAME AS LNAME " +
                 "  FROM BILL JOIN WAITER ON BILL.WAITER=WAITER.ID JOIN PEOPLE ON BILL.CREATEDBY=PEOPLE.NAME JOIN LOCATIONS ON bill.warehouse=LOCATIONS.ID JOIN CUSTOMERS ON substring(BILL.CUSTOMER,1,36) LIKE CUSTOMERS.ID " +
                 "  WHERE  ?(QBF_FILTER)   " +//praveen:removed +'%'
                 "  UNION ALL SELECT  CUSTOMERS.NAME, BILL_ARV.AMOUNT AS AMOUNT,CUSTOMERS.SEARCHKEY,WAITER.NAME AS WNAME,BILL_ARV.ID AS ID,WAITER.ID AS WID,LOCATIONS.NAME AS LNAME  " +
                 "  FROM BILL_ARV JOIN WAITER ON BILL_ARV.WAITER=WAITER.ID JOIN PEOPLE ON BILL_ARV.CREATEDBY=PEOPLE.NAME JOIN LOCATIONS ON bill_arv.warehouse=LOCATIONS.ID JOIN CUSTOMERS ON substring(BILL_arv.CUSTOMER,1,36) LIKE CUSTOMERS.ID"+
                 "  WHERE  ?(QBF_FILTER)   " +
                 "  ) AS WAITERWISE ORDER BY 7,4,1");
             report.clearlist();
             report.addField("NAME", com.openbravo.data.loader.Datas.STRING);
             report.addField("AMOUNT", com.openbravo.data.loader.Datas.DOUBLE);
            report.addField("SEARCHKEY", com.openbravo.data.loader.Datas.STRING);
            report.addField("WNAME", com.openbravo.data.loader.Datas.STRING);
             report.addField("ID", com.openbravo.data.loader.Datas.STRING);
             report.addField("WID", com.openbravo.data.loader.Datas.STRING);
             report.addField("LNAME", com.openbravo.data.loader.Datas.STRING);
            report.init1(m_App,1);
        }else{
            report.setreporttoempty();
            report.setReport("/com/openbravo/reports/waiterbillwise");
            report.setResourceBundle("com/openbravo/reports/costing_messages");
            report.setSentence("SELECT NAME,SUM(AMOUNT),ID,LNAME FROM (SELECT WAITER.NAME, SUM(BILL.AMOUNT) AS AMOUNT,WAITER.ID,LOCATIONS.NAME AS LNAME " +
                 " FROM BILL JOIN WAITER ON BILL.WAITER=WAITER.ID JOIN PEOPLE ON BILL.CREATEDBY=PEOPLE.NAME JOIN LOCATIONS ON bill.warehouse=LOCATIONS.ID " +
                 " WHERE  ?(QBF_FILTER)   " +
                 " GROUP BY WAITER.ID,WAITER.NAME,LNAME  "+
                 " UNION ALL SELECT WAITER.NAME, SUM(BILL_ARV.AMOUNT) AS AMOUNT,WAITER.ID,LOCATIONS.NAME AS LNAME  " +
                 " FROM BILL_ARV JOIN WAITER ON BILL_ARV.WAITER=WAITER.ID JOIN PEOPLE ON BILL_ARV.CREATEDBY=PEOPLE.NAME JOIN LOCATIONS ON bill_arv.warehouse=LOCATIONS.ID " +
                 " WHERE  ?(QBF_FILTER)   " +
                 " GROUP BY WAITER.ID,WAITER.NAME,LNAME )AS WAITERWISE GROUP BY ID,NAME,LNAME ORDER BY 4,1 ");
              report.clearlist();
              report.addField("NAME", com.openbravo.data.loader.Datas.STRING);
              report.addField("AMOUNT", com.openbravo.data.loader.Datas.DOUBLE);
              report.addField("ID", com.openbravo.data.loader.Datas.STRING);
              report.addField("LNAME", com.openbravo.data.loader.Datas.STRING);              
              report.init1(m_App,1);
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
