/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccountCreatorDialog.java
 *
 * Created on Apr 14, 2009, 2:55:17 PM
 */

package com.openbravo.pos.Accounts;

import com.openbravo.pos.forms.AppView;
import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
//import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author swathi
 */
public class AccountCreatorDialog extends javax.swing.JDialog {

    /** Creates new form AccountCreatorDialog */
     private AppView m_App;
    public AccountCreatorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    protected AccountCreatorDialog(Dialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AccountCreatorDialog(Frame parent,AppView app) {
        this(parent, true);
        this.m_App=app;
    }

    public AccountCreatorDialog(Dialog parent,AppView app) {
        this(parent, true);
        this.m_App=app;
    }

    protected static Window getWindow(Component parent) {
        if (parent == null) {
            return new JFrame();
        } else if (parent instanceof Frame || parent instanceof Dialog) {
            return (Window)parent;
        } else {
            return getWindow(parent.getParent());
        }
    }
 

    public static AccountCreatorDialog getDialog(Component parent,AppView app) {

        Window window = getWindow(parent);

        AccountCreatorDialog ct;

        if (window instanceof Frame) {
            ct = new AccountCreatorDialog((Frame) window,app);
        } else {
            ct = new AccountCreatorDialog((Dialog) window,app);
        }

        return ct;
    }
   public  void showDialog(){
       AccountCreator acc=new AccountCreator();
       acc.init(m_App);
       jPanel1.add(acc.getComponent());
       setVisible(true);
   }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        accountCreator1 = new com.openbravo.pos.Accounts.AccountCreator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accountCreator1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(accountCreator1, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.openbravo.pos.Accounts.AccountCreator accountCreator1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
